// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse, OASISSession } from './src/core/types';
import type { AuthModule } from './src/modules/Auth';
import type { AvatarModule } from './src/modules/Avatar';
import type { CelestialBodiesModule } from './src/modules/CelestialBodies';
import type { CelestialBodiesMetaDataModule } from './src/modules/CelestialBodiesMetaData';
import type { CelestialSpacesModule } from './src/modules/CelestialSpaces';
import type { ChaptersModule } from './src/modules/Chapters';
import type { CompetitionModule } from './src/modules/Competition';
import type { CosmicModule } from './src/modules/Cosmic';
import type { GamesModule } from './src/modules/Games';
import type { GeoHotSpotsModule } from './src/modules/GeoHotSpots';
import type { GeoNFTsModule } from './src/modules/GeoNFTs';
import type { HealthModule } from './src/modules/Health';
import type { HolonsModule } from './src/modules/Holons';
import type { HolonsMetaDataModule } from './src/modules/HolonsMetaData';
import type { InventoryItemsModule } from './src/modules/InventoryItems';
import type { LibrariesModule } from './src/modules/Libraries';
import type { MissionsModule } from './src/modules/Missions';
import type { NFTsModule } from './src/modules/NFTs';
import type { OAPPsModule } from './src/modules/OAPPs';
import type { ParksModule } from './src/modules/Parks';
import type { PluginsModule } from './src/modules/Plugins';
import type { QuestsModule } from './src/modules/Quests';
import type { RuntimesModule } from './src/modules/Runtimes';
import type { STARModule } from './src/modules/STAR';
import type { TemplatesModule } from './src/modules/Templates';
import type { ZomesModule } from './src/modules/Zomes';
import type { ZomesMetaDataModule } from './src/modules/ZomesMetaData';

export type { OASISResponse, OASISSession };

export interface STARClientOptions {
  baseUrl?: string;
  persistSession?: boolean;
  fetchImpl?: typeof fetch;
}

export declare class HttpClient {
  constructor(options?: { baseUrl?: string; tokenStore?: unknown; fetchImpl?: typeof fetch });
  setBaseUrl(baseUrl: string): void;
  request(verb: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, options?: Record<string, any>): Promise<OASISResponse>;
  get(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  post(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  put(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  delete(path: string, options?: Record<string, any>): Promise<OASISResponse>;
}

export declare class TokenStore {
  constructor(options?: { persist?: boolean });
  getSession(): OASISSession | null;
  getToken(): string | null;
  setSession(session: OASISSession | null): void;
  clear(): void;
}

export declare const DEFAULT_BASE_URL: string;

export declare class STARClient {
  constructor(options?: STARClientOptions);
  readonly http: HttpClient;
  readonly tokenStore: TokenStore;
  readonly auth: AuthModule;
  readonly avatar: AvatarModule;
  readonly celestialBodies: CelestialBodiesModule;
  readonly celestialBodiesMetaData: CelestialBodiesMetaDataModule;
  readonly celestialSpaces: CelestialSpacesModule;
  readonly chapters: ChaptersModule;
  readonly competition: CompetitionModule;
  readonly cosmic: CosmicModule;
  readonly games: GamesModule;
  readonly geoHotSpots: GeoHotSpotsModule;
  readonly geoNFTs: GeoNFTsModule;
  readonly health: HealthModule;
  readonly holons: HolonsModule;
  readonly holonsMetaData: HolonsMetaDataModule;
  readonly inventoryItems: InventoryItemsModule;
  readonly libraries: LibrariesModule;
  readonly missions: MissionsModule;
  readonly nFTs: NFTsModule;
  readonly oAPPs: OAPPsModule;
  readonly parks: ParksModule;
  readonly plugins: PluginsModule;
  readonly quests: QuestsModule;
  readonly runtimes: RuntimesModule;
  readonly sTAR: STARModule;
  readonly templates: TemplatesModule;
  readonly zomes: ZomesModule;
  readonly zomesMetaData: ZomesMetaDataModule;
  setBaseUrl(baseUrl: string): void;
  setToken(jwtToken: string, sessionExtras?: Partial<OASISSession>): void;
  starIgnite(args?: Record<string, any>): Promise<OASISResponse>;
  starExtinguish(args?: Record<string, any>): Promise<OASISResponse>;
  starStatus(args?: Record<string, any>): Promise<OASISResponse>;
}

export default STARClient;
