// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class AvatarModule {
  constructor(http: unknown);

  /** POST api/avatar/inventory */
  addItemToInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/add-xp */
  addXp(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/authenticate */
  authenticate(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/current */
  getCurrentAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory */
  getInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory/{itemId} */
  getInventoryItem(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/avatar/inventory/{itemId}/has */
  hasItem(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/avatar/inventory/{itemId} */
  removeItemFromInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/inventory/send-to-avatar */
  sendItemToAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/inventory/send-to-clan */
  sendItemToClan(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/avatar/set-active-quest */
  setActiveQuest(args?: Record<string, any>): Promise<OASISResponse>;
}
