'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/avatar (source: STAR WebAPI AvatarController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class AvatarModule {
  constructor(http) {
    this._http = http;

    // post api/avatar/inventory
    this.addItemToInventory = makeOperation(http, "api/avatar", "POST", "inventory");
    // post api/avatar/add-xp
    this.addXp = makeOperation(http, "api/avatar", "POST", "add-xp");
    // post api/avatar/authenticate
    this.authenticate = makeOperation(http, "api/avatar", "POST", "authenticate");
    // get api/avatar/current
    this.getCurrentAvatar = makeOperation(http, "api/avatar", "GET", "current");
    // get api/avatar/inventory
    this.getInventory = makeOperation(http, "api/avatar", "GET", "inventory");
    // get api/avatar/inventory/{itemId}
    this.getInventoryItem = makeOperation(http, "api/avatar", "GET", "inventory/{itemId}");
    // get api/avatar/inventory/{itemId}/has
    this.hasItem = makeOperation(http, "api/avatar", "GET", "inventory/{itemId}/has");
    // get api/avatar/inventory/has-by-name
    this.hasItemByName = makeOperation(http, "api/avatar", "GET", "inventory/has-by-name");
    // delete api/avatar/inventory/{itemId}
    this.removeItemFromInventory = makeOperation(http, "api/avatar", "DELETE", "inventory/{itemId}");
    // get api/avatar/inventory/search
    this.searchInventory = makeOperation(http, "api/avatar", "GET", "inventory/search");
    // post api/avatar/inventory/send-to-avatar
    this.sendItemToAvatar = makeOperation(http, "api/avatar", "POST", "inventory/send-to-avatar");
    // post api/avatar/inventory/send-to-clan
    this.sendItemToClan = makeOperation(http, "api/avatar", "POST", "inventory/send-to-clan");
    // post api/avatar/set-active-quest
    this.setActiveQuest = makeOperation(http, "api/avatar", "POST", "set-active-quest");
  }
}

module.exports = { AvatarModule };
