'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/celestialSpaces (source: STAR WebAPI CelestialSpacesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CelestialSpacesModule {
  constructor(http) {
    this._http = http;

    // post api/celestialSpaces/{id}/activate
    this.activateCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/activate");
    // post api/celestialSpaces/
    this.createCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "");
    // post api/celestialSpaces/create
    this.createCelestialSpaceWithOptions = makeOperation(http, "api/celestialSpaces", "POST", "create");
    // post api/celestialSpaces/{id}/deactivate
    this.deactivateCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/deactivate");
    // delete api/celestialSpaces/{id}
    this.deleteCelestialSpace = makeOperation(http, "api/celestialSpaces", "DELETE", "{id}");
    // post api/celestialSpaces/{id}/download
    this.downloadCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/download");
    // post api/celestialSpaces/{id}/edit
    this.editCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/edit");
    // get api/celestialSpaces/
    this.getAllCelestialSpaces = makeOperation(http, "api/celestialSpaces", "GET", "");
    // get api/celestialSpaces/{id}
    this.getCelestialSpace = makeOperation(http, "api/celestialSpaces", "GET", "{id}");
    // get api/celestialSpaces/{id}/versions
    this.getCelestialSpaceVersions = makeOperation(http, "api/celestialSpaces", "GET", "{id}/versions");
    // get api/celestialSpaces/by-type/{type}
    this.getCelestialSpacesByType = makeOperation(http, "api/celestialSpaces", "GET", "by-type/{type}");
    // get api/celestialSpaces/in-space/{parentSpaceId}
    this.getCelestialSpacesInSpace = makeOperation(http, "api/celestialSpaces", "GET", "in-space/{parentSpaceId}");
    // get api/celestialSpaces/load-all-for-avatar
    this.loadAllCelestialSpacesForAvatar = makeOperation(http, "api/celestialSpaces", "GET", "load-all-for-avatar");
    // get api/celestialSpaces/{id}/load
    this.loadCelestialSpace = makeOperation(http, "api/celestialSpaces", "GET", "{id}/load");
    // get api/celestialSpaces/load-from-path
    this.loadCelestialSpaceFromPath = makeOperation(http, "api/celestialSpaces", "GET", "load-from-path");
    // get api/celestialSpaces/load-from-published
    this.loadCelestialSpaceFromPublished = makeOperation(http, "api/celestialSpaces", "GET", "load-from-published");
    // get api/celestialSpaces/{id}/version/{version}
    this.loadCelestialSpaceVersion = makeOperation(http, "api/celestialSpaces", "GET", "{id}/version/{version}");
    // post api/celestialSpaces/{id}/publish
    this.publishCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/publish");
    // post api/celestialSpaces/{id}/republish
    this.republishCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/republish");
    // get api/celestialSpaces/search
    this.searchCelestialSpaces = makeOperation(http, "api/celestialSpaces", "GET", "search");
    // post api/celestialSpaces/{id}/unpublish
    this.unpublishCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/unpublish");
    // put api/celestialSpaces/{id}
    this.updateCelestialSpace = makeOperation(http, "api/celestialSpaces", "PUT", "{id}");
  }
}

module.exports = { CelestialSpacesModule };
