// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CelestialBodiesModule {
  constructor(http: unknown);

  /** POST api/celestialBodies/{id}/activate */
  activateCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/ */
  createCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/create */
  createCelestialBodyWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/deactivate */
  deactivateCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/celestialBodies/{id} */
  deleteCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/download */
  downloadCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/edit */
  editCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/ */
  getAllCelestialBodies(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/by-type/{type} */
  getCelestialBodiesByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/in-space/{spaceId} */
  getCelestialBodiesInSpace(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id} */
  getCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id}/versions */
  getCelestialBodyVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/load-all-for-avatar */
  loadAllCelestialBodiesForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id}/load */
  loadCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/load-from-path */
  loadCelestialBodyFromPath(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/load-from-published */
  loadCelestialBodyFromPublished(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id}/version/{version} */
  loadCelestialBodyVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/publish */
  publishCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/republish */
  republishCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/search */
  searchCelestialBodies(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/unpublish */
  unpublishCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/celestialBodies/{id} */
  updateCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;
}
