// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CelestialBodiesModule {
  constructor(http: unknown);

  /** POST api/celestialBodies/ */
  createCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/create */
  createCelestialBodyWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/celestialBodies/{id} */
  deleteCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/edit */
  editCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/ */
  getAllCelestialBodies(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/by-type/{type} */
  getCelestialBodiesByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/in-space/{spaceId} */
  getCelestialBodiesInSpace(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id} */
  getCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id}/versions */
  getCelestialBodyVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/celestialBodies/{id}/version/{version} */
  loadCelestialBodyVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/celestialBodies/{id}/publish */
  publishCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/celestialBodies/{id} */
  updateCelestialBody(args?: Record<string, any>): Promise<OASISResponse>;
}
