'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/celestialSpaces (source: STAR WebAPI CelestialSpacesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CelestialSpacesModule {
  constructor(http) {
    this._http = http;

    // POST api/celestialSpaces/{id}/activate (query: version)
    this.activateCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/activate", {"query":["version"]});
    // POST api/celestialSpaces/
    this.createCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "");
    // POST api/celestialSpaces/create
    this.createCelestialSpaceWithOptions = makeOperation(http, "api/celestialSpaces", "POST", "create");
    // POST api/celestialSpaces/{id}/deactivate (query: version)
    this.deactivateCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/celestialSpaces/{id}
    this.deleteCelestialSpace = makeOperation(http, "api/celestialSpaces", "DELETE", "{id}");
    // POST api/celestialSpaces/{id}/download (query: version, downloadPath, reInstall)
    this.downloadCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/celestialSpaces/{id}/edit
    this.editCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/edit");
    // GET api/celestialSpaces/
    this.getAllCelestialSpaces = makeOperation(http, "api/celestialSpaces", "GET", "");
    // GET api/celestialSpaces/{id}
    this.getCelestialSpace = makeOperation(http, "api/celestialSpaces", "GET", "{id}");
    // GET api/celestialSpaces/{id}/versions
    this.getCelestialSpaceVersions = makeOperation(http, "api/celestialSpaces", "GET", "{id}/versions");
    // GET api/celestialSpaces/by-type/{type}
    this.getCelestialSpacesByType = makeOperation(http, "api/celestialSpaces", "GET", "by-type/{type}");
    // GET api/celestialSpaces/in-space/{parentSpaceId}
    this.getCelestialSpacesInSpace = makeOperation(http, "api/celestialSpaces", "GET", "in-space/{parentSpaceId}");
    // GET api/celestialSpaces/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllCelestialSpacesForAvatar = makeOperation(http, "api/celestialSpaces", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/celestialSpaces/{id}/load (query: version, holonType)
    this.loadCelestialSpace = makeOperation(http, "api/celestialSpaces", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/celestialSpaces/load-from-path (query: path, holonType)
    this.loadCelestialSpaceFromPath = makeOperation(http, "api/celestialSpaces", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/celestialSpaces/load-from-published (query: publishedFilePath)
    this.loadCelestialSpaceFromPublished = makeOperation(http, "api/celestialSpaces", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/celestialSpaces/{id}/version/{version}
    this.loadCelestialSpaceVersion = makeOperation(http, "api/celestialSpaces", "GET", "{id}/version/{version}");
    // POST api/celestialSpaces/{id}/publish
    this.publishCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/publish");
    // POST api/celestialSpaces/{id}/republish (query: version)
    this.republishCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/republish", {"query":["version"]});
    // GET api/celestialSpaces/search (query: query)
    this.searchCelestialSpaces = makeOperation(http, "api/celestialSpaces", "GET", "search", {"query":["query"]});
    // POST api/celestialSpaces/{id}/unpublish (query: version)
    this.unpublishCelestialSpace = makeOperation(http, "api/celestialSpaces", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/celestialSpaces/{id}
    this.updateCelestialSpace = makeOperation(http, "api/celestialSpaces", "PUT", "{id}");
  }
}

module.exports = { CelestialSpacesModule };
