'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/celestialBodiesMetaData (source: STAR WebAPI CelestialBodiesMetaDataController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CelestialBodiesMetaDataModule {
  constructor(http) {
    this._http = http;

    // POST api/celestialBodiesMetaData/{id}/activate (query: version)
    this.activateCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/activate", {"query":["version"]});
    // POST api/celestialBodiesMetaData/{id}/clone
    this.cloneCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/clone");
    // POST api/celestialBodiesMetaData/
    this.createCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "");
    // POST api/celestialBodiesMetaData/create
    this.createCelestialBodyMetaDataWithOptions = makeOperation(http, "api/celestialBodiesMetaData", "POST", "create");
    // POST api/celestialBodiesMetaData/{id}/deactivate (query: version)
    this.deactivateCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/celestialBodiesMetaData/{id}
    this.deleteCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "DELETE", "{id}");
    // POST api/celestialBodiesMetaData/{id}/download
    this.downloadCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/download");
    // PUT api/celestialBodiesMetaData/{id}/edit
    this.editCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "PUT", "{id}/edit");
    // GET api/celestialBodiesMetaData/
    this.getAllCelestialBodiesMetaData = makeOperation(http, "api/celestialBodiesMetaData", "GET", "");
    // GET api/celestialBodiesMetaData/{id}
    this.getCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "GET", "{id}");
    // GET api/celestialBodiesMetaData/{id}/versions
    this.getCelestialBodyMetaDataVersions = makeOperation(http, "api/celestialBodiesMetaData", "GET", "{id}/versions");
    // GET api/celestialBodiesMetaData/load-all-for-avatar
    this.loadAllCelestialBodyMetaDataForAvatar = makeOperation(http, "api/celestialBodiesMetaData", "GET", "load-all-for-avatar");
    // GET api/celestialBodiesMetaData/load-from-path (query: path)
    this.loadCelestialBodyMetaDataFromPath = makeOperation(http, "api/celestialBodiesMetaData", "GET", "load-from-path", {"query":["path"]});
    // GET api/celestialBodiesMetaData/load-from-published (query: publishedFilePath)
    this.loadCelestialBodyMetaDataFromPublished = makeOperation(http, "api/celestialBodiesMetaData", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/celestialBodiesMetaData/{id}/versions/{version}
    this.loadCelestialBodyMetaDataVersion = makeOperation(http, "api/celestialBodiesMetaData", "GET", "{id}/versions/{version}");
    // POST api/celestialBodiesMetaData/{id}/publish
    this.publishCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/publish");
    // POST api/celestialBodiesMetaData/{id}/republish (query: version)
    this.republishCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/republish", {"query":["version"]});
    // POST api/celestialBodiesMetaData/search
    this.searchCelestialBodiesMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "search");
    // POST api/celestialBodiesMetaData/{id}/unpublish (query: version)
    this.unpublishCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/celestialBodiesMetaData/{id}
    this.updateCelestialBodyMetaData = makeOperation(http, "api/celestialBodiesMetaData", "PUT", "{id}");
  }
}

module.exports = { CelestialBodiesMetaDataModule };
