'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/chapters (source: STAR WebAPI ChaptersController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ChaptersModule {
  constructor(http) {
    this._http = http;

    // POST api/chapters/{id}/activate (query: version)
    this.activateChapter = makeOperation(http, "api/chapters", "POST", "{id}/activate", {"query":["version"]});
    // POST api/chapters/
    this.createChapter = makeOperation(http, "api/chapters", "POST", "");
    // POST api/chapters/create
    this.createChapterWithOptions = makeOperation(http, "api/chapters", "POST", "create");
    // POST api/chapters/{id}/deactivate (query: version)
    this.deactivateChapter = makeOperation(http, "api/chapters", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/chapters/{id}
    this.deleteChapter = makeOperation(http, "api/chapters", "DELETE", "{id}");
    // POST api/chapters/{id}/download (query: version, downloadPath, reInstall)
    this.downloadChapter = makeOperation(http, "api/chapters", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/chapters/{id}/edit
    this.editChapter = makeOperation(http, "api/chapters", "POST", "{id}/edit");
    // GET api/chapters/
    this.getAllChapters = makeOperation(http, "api/chapters", "GET", "");
    // GET api/chapters/{id}
    this.getChapter = makeOperation(http, "api/chapters", "GET", "{id}");
    // GET api/chapters/{id}/versions
    this.getChapterVersions = makeOperation(http, "api/chapters", "GET", "{id}/versions");
    // GET api/chapters/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllChaptersForAvatar = makeOperation(http, "api/chapters", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/chapters/{id}/load (query: version, holonType)
    this.loadChapter = makeOperation(http, "api/chapters", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/chapters/load-from-path (query: path, holonType)
    this.loadChapterFromPath = makeOperation(http, "api/chapters", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/chapters/load-from-published (query: publishedFilePath)
    this.loadChapterFromPublished = makeOperation(http, "api/chapters", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/chapters/{id}/version/{version}
    this.loadChapterVersion = makeOperation(http, "api/chapters", "GET", "{id}/version/{version}");
    // POST api/chapters/{id}/publish
    this.publishChapter = makeOperation(http, "api/chapters", "POST", "{id}/publish");
    // POST api/chapters/{id}/republish (query: version)
    this.republishChapter = makeOperation(http, "api/chapters", "POST", "{id}/republish", {"query":["version"]});
    // GET api/chapters/search (query: query)
    this.searchChapters = makeOperation(http, "api/chapters", "GET", "search", {"query":["query"]});
    // POST api/chapters/{id}/unpublish (query: version)
    this.unpublishChapter = makeOperation(http, "api/chapters", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/chapters/{id}
    this.updateChapter = makeOperation(http, "api/chapters", "PUT", "{id}");
  }
}

module.exports = { ChaptersModule };
