'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/chapters (source: STAR WebAPI ChaptersController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ChaptersModule {
  constructor(http) {
    this._http = http;

    // post api/chapters/{id}/activate
    this.activateChapter = makeOperation(http, "api/chapters", "POST", "{id}/activate");
    // post api/chapters/
    this.createChapter = makeOperation(http, "api/chapters", "POST", "");
    // post api/chapters/create
    this.createChapterWithOptions = makeOperation(http, "api/chapters", "POST", "create");
    // post api/chapters/{id}/deactivate
    this.deactivateChapter = makeOperation(http, "api/chapters", "POST", "{id}/deactivate");
    // delete api/chapters/{id}
    this.deleteChapter = makeOperation(http, "api/chapters", "DELETE", "{id}");
    // post api/chapters/{id}/download
    this.downloadChapter = makeOperation(http, "api/chapters", "POST", "{id}/download");
    // post api/chapters/{id}/edit
    this.editChapter = makeOperation(http, "api/chapters", "POST", "{id}/edit");
    // get api/chapters/
    this.getAllChapters = makeOperation(http, "api/chapters", "GET", "");
    // get api/chapters/{id}
    this.getChapter = makeOperation(http, "api/chapters", "GET", "{id}");
    // get api/chapters/{id}/versions
    this.getChapterVersions = makeOperation(http, "api/chapters", "GET", "{id}/versions");
    // get api/chapters/load-all-for-avatar
    this.loadAllChaptersForAvatar = makeOperation(http, "api/chapters", "GET", "load-all-for-avatar");
    // get api/chapters/{id}/load
    this.loadChapter = makeOperation(http, "api/chapters", "GET", "{id}/load");
    // get api/chapters/load-from-path
    this.loadChapterFromPath = makeOperation(http, "api/chapters", "GET", "load-from-path");
    // get api/chapters/load-from-published
    this.loadChapterFromPublished = makeOperation(http, "api/chapters", "GET", "load-from-published");
    // get api/chapters/{id}/version/{version}
    this.loadChapterVersion = makeOperation(http, "api/chapters", "GET", "{id}/version/{version}");
    // post api/chapters/{id}/publish
    this.publishChapter = makeOperation(http, "api/chapters", "POST", "{id}/publish");
    // post api/chapters/{id}/republish
    this.republishChapter = makeOperation(http, "api/chapters", "POST", "{id}/republish");
    // get api/chapters/search
    this.searchChapters = makeOperation(http, "api/chapters", "GET", "search");
    // post api/chapters/{id}/unpublish
    this.unpublishChapter = makeOperation(http, "api/chapters", "POST", "{id}/unpublish");
    // put api/chapters/{id}
    this.updateChapter = makeOperation(http, "api/chapters", "PUT", "{id}");
  }
}

module.exports = { ChaptersModule };
