// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CompetitionModule {
  constructor(http: unknown);

  /** GET api/competition/tournaments */
  getActiveTournaments(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/leagues/{competitionType}/{seasonType} */
  getAvailableLeagues(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/league/{avatarId}/{competitionType}/{seasonType} */
  getAvatarLeague(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/rank/{avatarId}/{competitionType}/{seasonType} */
  getAvatarRank(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/leaderboard/{competitionType}/{seasonType} */
  getLeaderboard(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/my-league/{competitionType}/{seasonType} */
  getMyLeague(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/my-rank/{competitionType}/{seasonType} */
  getMyRank(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/competition/stats/{competitionType}/{seasonType} */
  getMyStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/competition/tournaments/{tournamentId}/join */
  joinTournament(args?: Record<string, any>): Promise<OASISResponse>;
}
