'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/competition (source: STAR WebAPI CompetitionController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CompetitionModule {
  constructor(http) {
    this._http = http;

    // GET api/competition/tournaments (query: competitionType)
    this.getActiveTournaments = makeOperation(http, "api/competition", "GET", "tournaments", {"query":["competitionType"]});
    // GET api/competition/leagues/{competitionType}/{seasonType}
    this.getAvailableLeagues = makeOperation(http, "api/competition", "GET", "leagues/{competitionType}/{seasonType}");
    // GET api/competition/league/{avatarId}/{competitionType}/{seasonType}
    this.getAvatarLeague = makeOperation(http, "api/competition", "GET", "league/{avatarId}/{competitionType}/{seasonType}");
    // GET api/competition/rank/{avatarId}/{competitionType}/{seasonType}
    this.getAvatarRank = makeOperation(http, "api/competition", "GET", "rank/{avatarId}/{competitionType}/{seasonType}");
    // GET api/competition/leaderboard/{competitionType}/{seasonType} (query: limit, offset)
    this.getLeaderboard = makeOperation(http, "api/competition", "GET", "leaderboard/{competitionType}/{seasonType}", {"query":["limit","offset"]});
    // GET api/competition/my-league/{competitionType}/{seasonType}
    this.getMyLeague = makeOperation(http, "api/competition", "GET", "my-league/{competitionType}/{seasonType}");
    // GET api/competition/my-rank/{competitionType}/{seasonType}
    this.getMyRank = makeOperation(http, "api/competition", "GET", "my-rank/{competitionType}/{seasonType}");
    // GET api/competition/stats/{competitionType}/{seasonType}
    this.getMyStats = makeOperation(http, "api/competition", "GET", "stats/{competitionType}/{seasonType}");
    // POST api/competition/tournaments/{tournamentId}/join
    this.joinTournament = makeOperation(http, "api/competition", "POST", "tournaments/{tournamentId}/join");
  }
}

module.exports = { CompetitionModule };
