'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/cosmic (source: STAR WebAPI CosmicController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CosmicModule {
  constructor(http) {
    this._http = http;

    // post api/cosmic/galaxy/{parentGalaxyId}/asteroid
    this.addAsteroid = makeOperation(http, "api/cosmic", "POST", "galaxy/{parentGalaxyId}/asteroid");
    // post api/cosmic/galaxy/{parentGalaxyId}/comet
    this.addComet = makeOperation(http, "api/cosmic", "POST", "galaxy/{parentGalaxyId}/comet");
    // post api/cosmic/galaxy-cluster/{parentGalaxyClusterId}/galaxy
    this.addGalaxy = makeOperation(http, "api/cosmic", "POST", "galaxy-cluster/{parentGalaxyClusterId}/galaxy");
    // post api/cosmic/universe/{parentUniverseId}/galaxy-cluster
    this.addGalaxyCluster = makeOperation(http, "api/cosmic", "POST", "universe/{parentUniverseId}/galaxy-cluster");
    // post api/cosmic/galaxy/{parentGalaxyId}/meteroid
    this.addMeteroid = makeOperation(http, "api/cosmic", "POST", "galaxy/{parentGalaxyId}/meteroid");
    // post api/cosmic/planet/{parentPlanetId}/moon
    this.addMoon = makeOperation(http, "api/cosmic", "POST", "planet/{parentPlanetId}/moon");
    // post api/cosmic/omniverse/{parentOmniverseId}/multiverse
    this.addMultiverse = makeOperation(http, "api/cosmic", "POST", "omniverse/{parentOmniverseId}/multiverse");
    // post api/cosmic/solar-system/{parentSolarSystemId}/planet
    this.addPlanet = makeOperation(http, "api/cosmic", "POST", "solar-system/{parentSolarSystemId}/planet");
    // post api/cosmic/galaxy/{parentGalaxyId}/solar-system
    this.addSolarSystem = makeOperation(http, "api/cosmic", "POST", "galaxy/{parentGalaxyId}/solar-system");
    // post api/cosmic/galaxy/{parentGalaxyId}/star
    this.addStar = makeOperation(http, "api/cosmic", "POST", "galaxy/{parentGalaxyId}/star");
    // post api/cosmic/multiverse/{parentMultiverseId}/universe
    this.addUniverse = makeOperation(http, "api/cosmic", "POST", "multiverse/{parentMultiverseId}/universe");
    // delete api/cosmic/asteroid/{asteroidId}
    this.deleteAsteroid = makeOperation(http, "api/cosmic", "DELETE", "asteroid/{asteroidId}");
    // delete api/cosmic/blackhole/{blackHoleId}
    this.deleteBlackHole = makeOperation(http, "api/cosmic", "DELETE", "blackhole/{blackHoleId}");
    // delete api/cosmic/comet/{cometId}
    this.deleteComet = makeOperation(http, "api/cosmic", "DELETE", "comet/{cometId}");
    // delete api/cosmic/cosmic-ray/{rayId}
    this.deleteCosmicRay = makeOperation(http, "api/cosmic", "DELETE", "cosmic-ray/{rayId}");
    // delete api/cosmic/cosmic-wave/{waveId}
    this.deleteCosmicWave = makeOperation(http, "api/cosmic", "DELETE", "cosmic-wave/{waveId}");
    // delete api/cosmic/galaxy/{galaxyId}
    this.deleteGalaxy = makeOperation(http, "api/cosmic", "DELETE", "galaxy/{galaxyId}");
    // delete api/cosmic/galaxy-cluster/{galaxyClusterId}
    this.deleteGalaxyCluster = makeOperation(http, "api/cosmic", "DELETE", "galaxy-cluster/{galaxyClusterId}");
    // delete api/cosmic/gravitational-wave/{waveId}
    this.deleteGravitationalWave = makeOperation(http, "api/cosmic", "DELETE", "gravitational-wave/{waveId}");
    // delete api/cosmic/meteroid/{meteroidId}
    this.deleteMeteroid = makeOperation(http, "api/cosmic", "DELETE", "meteroid/{meteroidId}");
    // delete api/cosmic/moon/{moonId}
    this.deleteMoon = makeOperation(http, "api/cosmic", "DELETE", "moon/{moonId}");
    // delete api/cosmic/multiverse/{multiverseId}
    this.deleteMultiverse = makeOperation(http, "api/cosmic", "DELETE", "multiverse/{multiverseId}");
    // delete api/cosmic/nebula/{nebulaId}
    this.deleteNebula = makeOperation(http, "api/cosmic", "DELETE", "nebula/{nebulaId}");
    // delete api/cosmic/omniverse/{omniverseId}
    this.deleteOmniverse = makeOperation(http, "api/cosmic", "DELETE", "omniverse/{omniverseId}");
    // delete api/cosmic/planet/{planetId}
    this.deletePlanet = makeOperation(http, "api/cosmic", "DELETE", "planet/{planetId}");
    // delete api/cosmic/portal/{portalId}
    this.deletePortal = makeOperation(http, "api/cosmic", "DELETE", "portal/{portalId}");
    // delete api/cosmic/solar-system/{solarSystemId}
    this.deleteSolarSystem = makeOperation(http, "api/cosmic", "DELETE", "solar-system/{solarSystemId}");
    // delete api/cosmic/spacetime-abnormally/{abnormallyId}
    this.deleteSpaceTimeAbnormally = makeOperation(http, "api/cosmic", "DELETE", "spacetime-abnormally/{abnormallyId}");
    // delete api/cosmic/spacetime-distortion/{distortionId}
    this.deleteSpaceTimeDistortion = makeOperation(http, "api/cosmic", "DELETE", "spacetime-distortion/{distortionId}");
    // delete api/cosmic/star/{starId}
    this.deleteStar = makeOperation(http, "api/cosmic", "DELETE", "star/{starId}");
    // delete api/cosmic/stardust/{starDustId}
    this.deleteStarDust = makeOperation(http, "api/cosmic", "DELETE", "stardust/{starDustId}");
    // delete api/cosmic/stargate/{starGateId}
    this.deleteStarGate = makeOperation(http, "api/cosmic", "DELETE", "stargate/{starGateId}");
    // delete api/cosmic/superverse/{superVerseId}
    this.deleteSuperVerse = makeOperation(http, "api/cosmic", "DELETE", "superverse/{superVerseId}");
    // delete api/cosmic/temporal-rift/{riftId}
    this.deleteTemporalRift = makeOperation(http, "api/cosmic", "DELETE", "temporal-rift/{riftId}");
    // delete api/cosmic/universe/{universeId}
    this.deleteUniverse = makeOperation(http, "api/cosmic", "DELETE", "universe/{universeId}");
    // delete api/cosmic/wormhole/{wormHoleId}
    this.deleteWormHole = makeOperation(http, "api/cosmic", "DELETE", "wormhole/{wormHoleId}");
    // get api/cosmic/children/{parentId}
    this.getChildrenForParent = makeOperation(http, "api/cosmic", "GET", "children/{parentId}");
    // get api/cosmic/galaxy/{galaxyId}/moons
    this.getMoonsForGalaxy = makeOperation(http, "api/cosmic", "GET", "galaxy/{galaxyId}/moons");
    // get api/cosmic/omniverse
    this.getOmniverse = makeOperation(http, "api/cosmic", "GET", "omniverse");
    // get api/cosmic/galaxy/{galaxyId}/planets
    this.getPlanetsForGalaxy = makeOperation(http, "api/cosmic", "GET", "galaxy/{galaxyId}/planets");
    // get api/cosmic/solar-system/{solarSystemId}/planets
    this.getPlanetsForSolarSystem = makeOperation(http, "api/cosmic", "GET", "solar-system/{solarSystemId}/planets");
    // get api/cosmic/galaxy/{galaxyId}/solar-systems
    this.getSolarSystemsForGalaxy = makeOperation(http, "api/cosmic", "GET", "galaxy/{galaxyId}/solar-systems");
    // get api/cosmic/galaxy/{galaxyId}/stars
    this.getStarsForGalaxy = makeOperation(http, "api/cosmic", "GET", "galaxy/{galaxyId}/stars");
    // post api/cosmic/omniverse
    this.saveOmniverse = makeOperation(http, "api/cosmic", "POST", "omniverse");
    // get api/cosmic/search-children
    this.searchChildrenForParent = makeOperation(http, "api/cosmic", "GET", "search-children");
    // get api/cosmic/search-holons
    this.searchHolonsForParent = makeOperation(http, "api/cosmic", "GET", "search-holons");
    // get api/cosmic/search-holons-sync
    this.searchHolonsForParentSync = makeOperation(http, "api/cosmic", "GET", "search-holons-sync");
    // put api/cosmic/asteroid
    this.updateAsteroid = makeOperation(http, "api/cosmic", "PUT", "asteroid");
    // put api/cosmic/blackhole
    this.updateBlackHole = makeOperation(http, "api/cosmic", "PUT", "blackhole");
    // put api/cosmic/comet
    this.updateComet = makeOperation(http, "api/cosmic", "PUT", "comet");
    // put api/cosmic/cosmic-ray
    this.updateCosmicRay = makeOperation(http, "api/cosmic", "PUT", "cosmic-ray");
    // put api/cosmic/cosmic-wave
    this.updateCosmicWave = makeOperation(http, "api/cosmic", "PUT", "cosmic-wave");
    // put api/cosmic/galaxy
    this.updateGalaxy = makeOperation(http, "api/cosmic", "PUT", "galaxy");
    // put api/cosmic/galaxy-cluster
    this.updateGalaxyCluster = makeOperation(http, "api/cosmic", "PUT", "galaxy-cluster");
    // put api/cosmic/gravitational-wave
    this.updateGravitationalWave = makeOperation(http, "api/cosmic", "PUT", "gravitational-wave");
    // put api/cosmic/meteroid
    this.updateMeteroid = makeOperation(http, "api/cosmic", "PUT", "meteroid");
    // put api/cosmic/moon
    this.updateMoon = makeOperation(http, "api/cosmic", "PUT", "moon");
    // put api/cosmic/multiverse
    this.updateMultiverse = makeOperation(http, "api/cosmic", "PUT", "multiverse");
    // put api/cosmic/nebula
    this.updateNebula = makeOperation(http, "api/cosmic", "PUT", "nebula");
    // put api/cosmic/omniverse
    this.updateOmniverse = makeOperation(http, "api/cosmic", "PUT", "omniverse");
    // put api/cosmic/planet
    this.updatePlanet = makeOperation(http, "api/cosmic", "PUT", "planet");
    // put api/cosmic/portal
    this.updatePortal = makeOperation(http, "api/cosmic", "PUT", "portal");
    // put api/cosmic/solar-system
    this.updateSolarSystem = makeOperation(http, "api/cosmic", "PUT", "solar-system");
    // put api/cosmic/spacetime-abnormally
    this.updateSpaceTimeAbnormally = makeOperation(http, "api/cosmic", "PUT", "spacetime-abnormally");
    // put api/cosmic/spacetime-distortion
    this.updateSpaceTimeDistortion = makeOperation(http, "api/cosmic", "PUT", "spacetime-distortion");
    // put api/cosmic/star
    this.updateStar = makeOperation(http, "api/cosmic", "PUT", "star");
    // put api/cosmic/stardust
    this.updateStarDust = makeOperation(http, "api/cosmic", "PUT", "stardust");
    // put api/cosmic/stargate
    this.updateStarGate = makeOperation(http, "api/cosmic", "PUT", "stargate");
    // put api/cosmic/superverse
    this.updateSuperVerse = makeOperation(http, "api/cosmic", "PUT", "superverse");
    // put api/cosmic/temporal-rift
    this.updateTemporalRift = makeOperation(http, "api/cosmic", "PUT", "temporal-rift");
    // put api/cosmic/universe
    this.updateUniverse = makeOperation(http, "api/cosmic", "PUT", "universe");
    // put api/cosmic/wormhole
    this.updateWormHole = makeOperation(http, "api/cosmic", "PUT", "wormhole");
  }
}

module.exports = { CosmicModule };
