// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CosmicModule {
  constructor(http: unknown);

  /** POST api/cosmic/galaxy/{parentGalaxyId}/asteroid */
  addAsteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/comet */
  addComet(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy-cluster/{parentGalaxyClusterId}/galaxy */
  addGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/universe/{parentUniverseId}/galaxy-cluster */
  addGalaxyCluster(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/meteroid */
  addMeteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/planet/{parentPlanetId}/moon */
  addMoon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/omniverse/{parentOmniverseId}/multiverse */
  addMultiverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/solar-system/{parentSolarSystemId}/planet */
  addPlanet(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/solar-system */
  addSolarSystem(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/star */
  addStar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/multiverse/{parentMultiverseId}/universe */
  addUniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/moons */
  getMoonsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/omniverse */
  getOmniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/planets */
  getPlanetsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/solar-system/{solarSystemId}/planets */
  getPlanetsForSolarSystem(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/solar-systems */
  getSolarSystemsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/stars */
  getStarsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/omniverse */
  saveOmniverse(args?: Record<string, any>): Promise<OASISResponse>;
}
