// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CosmicModule {
  constructor(http: unknown);

  /** POST api/cosmic/galaxy/{parentGalaxyId}/asteroid */
  addAsteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/comet */
  addComet(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy-cluster/{parentGalaxyClusterId}/galaxy */
  addGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/universe/{parentUniverseId}/galaxy-cluster */
  addGalaxyCluster(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/meteroid */
  addMeteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/planet/{parentPlanetId}/moon */
  addMoon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/omniverse/{parentOmniverseId}/multiverse */
  addMultiverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/solar-system/{parentSolarSystemId}/planet */
  addPlanet(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/solar-system */
  addSolarSystem(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/galaxy/{parentGalaxyId}/star */
  addStar(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/multiverse/{parentMultiverseId}/universe */
  addUniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/asteroid/{asteroidId} */
  deleteAsteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/blackhole/{blackHoleId} */
  deleteBlackHole(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/comet/{cometId} */
  deleteComet(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/cosmic-ray/{rayId} */
  deleteCosmicRay(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/cosmic-wave/{waveId} */
  deleteCosmicWave(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/galaxy/{galaxyId} */
  deleteGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/galaxy-cluster/{galaxyClusterId} */
  deleteGalaxyCluster(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/gravitational-wave/{waveId} */
  deleteGravitationalWave(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/meteroid/{meteroidId} */
  deleteMeteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/moon/{moonId} */
  deleteMoon(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/multiverse/{multiverseId} */
  deleteMultiverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/nebula/{nebulaId} */
  deleteNebula(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/omniverse/{omniverseId} */
  deleteOmniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/planet/{planetId} */
  deletePlanet(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/portal/{portalId} */
  deletePortal(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/solar-system/{solarSystemId} */
  deleteSolarSystem(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/spacetime-abnormally/{abnormallyId} */
  deleteSpaceTimeAbnormally(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/spacetime-distortion/{distortionId} */
  deleteSpaceTimeDistortion(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/star/{starId} */
  deleteStar(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/stardust/{starDustId} */
  deleteStarDust(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/stargate/{starGateId} */
  deleteStarGate(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/superverse/{superVerseId} */
  deleteSuperVerse(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/temporal-rift/{riftId} */
  deleteTemporalRift(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/universe/{universeId} */
  deleteUniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/cosmic/wormhole/{wormHoleId} */
  deleteWormHole(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/children/{parentId} */
  getChildrenForParent(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/moons */
  getMoonsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/omniverse */
  getOmniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/planets */
  getPlanetsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/solar-system/{solarSystemId}/planets */
  getPlanetsForSolarSystem(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/solar-systems */
  getSolarSystemsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/galaxy/{galaxyId}/stars */
  getStarsForGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/cosmic/omniverse */
  saveOmniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/search-children */
  searchChildrenForParent(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/search-holons */
  searchHolonsForParent(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/cosmic/search-holons-sync */
  searchHolonsForParentSync(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/asteroid */
  updateAsteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/blackhole */
  updateBlackHole(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/comet */
  updateComet(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/cosmic-ray */
  updateCosmicRay(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/cosmic-wave */
  updateCosmicWave(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/galaxy */
  updateGalaxy(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/galaxy-cluster */
  updateGalaxyCluster(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/gravitational-wave */
  updateGravitationalWave(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/meteroid */
  updateMeteroid(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/moon */
  updateMoon(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/multiverse */
  updateMultiverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/nebula */
  updateNebula(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/omniverse */
  updateOmniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/planet */
  updatePlanet(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/portal */
  updatePortal(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/solar-system */
  updateSolarSystem(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/spacetime-abnormally */
  updateSpaceTimeAbnormally(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/spacetime-distortion */
  updateSpaceTimeDistortion(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/star */
  updateStar(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/stardust */
  updateStarDust(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/stargate */
  updateStarGate(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/superverse */
  updateSuperVerse(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/temporal-rift */
  updateTemporalRift(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/universe */
  updateUniverse(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/cosmic/wormhole */
  updateWormHole(args?: Record<string, any>): Promise<OASISResponse>;
}
