'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/games (source: STAR WebAPI GamesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class GamesModule {
  constructor(http) {
    this._http = http;

    // post api/games/{id}/activate (query: version)
    this.activateGame = makeOperation(http, "api/games", "POST", "{id}/activate", {"query":["version"]});
    // post api/games/shared-inventory/add
    this.addItemToInventory = makeOperation(http, "api/games", "POST", "shared-inventory/add");
    // post api/games/{gameId}/input/bind-keys
    this.bindKeys = makeOperation(http, "api/games", "POST", "{gameId}/input/bind-keys");
    // post api/games/{id}/clone
    this.cloneGame = makeOperation(http, "api/games", "POST", "{id}/clone");
    // post api/games/
    this.createGame = makeOperation(http, "api/games", "POST", "");
    // post api/games/create
    this.createGameWithOptions = makeOperation(http, "api/games", "POST", "create");
    // post api/games/{id}/deactivate (query: version)
    this.deactivateGame = makeOperation(http, "api/games", "POST", "{id}/deactivate", {"query":["version"]});
    // delete api/games/{id}
    this.deleteGame = makeOperation(http, "api/games", "DELETE", "{id}");
    // post api/games/{id}/download (query: version, downloadPath, reInstall)
    this.downloadGame = makeOperation(http, "api/games", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // post api/games/{id}/edit
    this.editGame = makeOperation(http, "api/games", "POST", "{id}/edit");
    // post api/games/{gameId}/end
    this.endGame = makeOperation(http, "api/games", "POST", "{gameId}/end");
    // get api/games/
    this.getAllGames = makeOperation(http, "api/games", "GET", "");
    // get api/games/karma
    this.getAvatarKarma = makeOperation(http, "api/games", "GET", "karma");
    // get api/games/cross-game-quests
    this.getCrossGameQuests = makeOperation(http, "api/games", "GET", "cross-game-quests");
    // get api/games/{id}
    this.getGame = makeOperation(http, "api/games", "GET", "{id}");
    // get api/games/{id}/versions
    this.getGameVersions = makeOperation(http, "api/games", "GET", "{id}/versions");
    // get api/games/by-type/{type}
    this.getGamesByType = makeOperation(http, "api/games", "GET", "by-type/{type}");
    // get api/games/{gameId}/input/bind-keys
    this.getKeyBindings = makeOperation(http, "api/games", "GET", "{gameId}/input/bind-keys");
    // get api/games/{gameId}/audio/master-volume
    this.getMasterVolume = makeOperation(http, "api/games", "GET", "{gameId}/audio/master-volume");
    // get api/games/shared-inventory
    this.getSharedInventory = makeOperation(http, "api/games", "GET", "shared-inventory");
    // get api/games/{gameId}/audio/sound-volume
    this.getSoundVolume = makeOperation(http, "api/games", "GET", "{gameId}/audio/sound-volume");
    // get api/games/{gameId}/video/setting
    this.getVideoSetting = makeOperation(http, "api/games", "GET", "{gameId}/video/setting");
    // get api/games/{gameId}/audio/voice-volume
    this.getVoiceVolume = makeOperation(http, "api/games", "GET", "{gameId}/audio/voice-volume");
    // get api/games/shared-inventory/{itemId}/has
    this.hasItem = makeOperation(http, "api/games", "GET", "shared-inventory/{itemId}/has");
    // get api/games/shared-inventory/has-by-name (query: itemName)
    this.hasItemByName = makeOperation(http, "api/games", "GET", "shared-inventory/has-by-name", {"query":["itemName"]});
    // post api/games/{id}/install (query: version, installPath)
    this.installGame = makeOperation(http, "api/games", "POST", "{id}/install", {"query":["version","installPath"]});
    // post api/games/{gameId}/areas/jump
    this.jumpToArea = makeOperation(http, "api/games", "POST", "{gameId}/areas/jump");
    // post api/games/{gameId}/levels/{level}/jump
    this.jumpToLevel = makeOperation(http, "api/games", "POST", "{gameId}/levels/{level}/jump");
    // post api/games/{gameId}/levels/{level}/jump-to-point
    this.jumpToPointInLevel = makeOperation(http, "api/games", "POST", "{gameId}/levels/{level}/jump-to-point");
    // get api/games/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllGamesForAvatar = makeOperation(http, "api/games", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // post api/games/{gameId}/areas/load
    this.loadArea = makeOperation(http, "api/games", "POST", "{gameId}/areas/load");
    // post api/games/{gameId}/load
    this.loadGame = makeOperation(http, "api/games", "POST", "{gameId}/load");
    // get api/games/{id}/load (query: version, holonType)
    this.loadGameById = makeOperation(http, "api/games", "GET", "{id}/load", {"query":["version","holonType"]});
    // get api/games/load-from-path (query: path, holonType)
    this.loadGameFromPath = makeOperation(http, "api/games", "GET", "load-from-path", {"query":["path","holonType"]});
    // get api/games/load-from-published (query: publishedFilePath)
    this.loadGameFromPublished = makeOperation(http, "api/games", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // get api/games/{id}/version/{version}
    this.loadGameVersion = makeOperation(http, "api/games", "GET", "{id}/version/{version}");
    // post api/games/{gameId}/levels/{level}/load
    this.loadLevel = makeOperation(http, "api/games", "POST", "{gameId}/levels/{level}/load");
    // post api/games/{id}/publish
    this.publishGame = makeOperation(http, "api/games", "POST", "{id}/publish");
    // delete api/games/shared-inventory/{itemId}
    this.removeItemFromInventory = makeOperation(http, "api/games", "DELETE", "shared-inventory/{itemId}");
    // post api/games/{id}/republish
    this.republishGame = makeOperation(http, "api/games", "POST", "{id}/republish");
    // get api/games/search (query: query)
    this.searchGames = makeOperation(http, "api/games", "GET", "search", {"query":["query"]});
    // post api/games/{gameId}/audio/master-volume
    this.setMasterVolume = makeOperation(http, "api/games", "POST", "{gameId}/audio/master-volume");
    // post api/games/{gameId}/audio/sound-volume
    this.setSoundVolume = makeOperation(http, "api/games", "POST", "{gameId}/audio/sound-volume");
    // post api/games/{gameId}/video/setting
    this.setVideoSetting = makeOperation(http, "api/games", "POST", "{gameId}/video/setting");
    // post api/games/{gameId}/audio/voice-volume
    this.setVoiceVolume = makeOperation(http, "api/games", "POST", "{gameId}/audio/voice-volume");
    // post api/games/{gameId}/ui/credits
    this.showCredits = makeOperation(http, "api/games", "POST", "{gameId}/ui/credits");
    // post api/games/{gameId}/ui/main-menu
    this.showMainMenu = makeOperation(http, "api/games", "POST", "{gameId}/ui/main-menu");
    // post api/games/{gameId}/ui/options
    this.showOptions = makeOperation(http, "api/games", "POST", "{gameId}/ui/options");
    // post api/games/{gameId}/ui/title-screen
    this.showTitleScreen = makeOperation(http, "api/games", "POST", "{gameId}/ui/title-screen");
    // post api/games/{gameId}/start
    this.startGame = makeOperation(http, "api/games", "POST", "{gameId}/start");
    // post api/games/{gameId}/areas/{areaId}/unload
    this.unloadArea = makeOperation(http, "api/games", "POST", "{gameId}/areas/{areaId}/unload");
    // post api/games/{gameId}/unload
    this.unloadGame = makeOperation(http, "api/games", "POST", "{gameId}/unload");
    // post api/games/{gameId}/levels/{level}/unload
    this.unloadLevel = makeOperation(http, "api/games", "POST", "{gameId}/levels/{level}/unload");
    // post api/games/{id}/unpublish (query: version)
    this.unpublishGame = makeOperation(http, "api/games", "POST", "{id}/unpublish", {"query":["version"]});
    // put api/games/{id}
    this.updateGame = makeOperation(http, "api/games", "PUT", "{id}");
  }
}

module.exports = { GamesModule };
