// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class GamesModule {
  constructor(http: unknown);

  /** POST api/games/shared-inventory/add */
  addItemToInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/input/bind-keys */
  bindKeys(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{id}/clone */
  cloneGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/ */
  createGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/create */
  createGameWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/games/{id} */
  deleteGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{id}/edit */
  editGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/end */
  endGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/ */
  getAllGames(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/karma */
  getAvatarKarma(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/cross-game-quests */
  getCrossGameQuests(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{id} */
  getGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/by-type/{type} */
  getGamesByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{id}/versions */
  getGameVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{gameId}/input/bind-keys */
  getKeyBindings(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{gameId}/audio/master-volume */
  getMasterVolume(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/shared-inventory */
  getSharedInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{gameId}/audio/sound-volume */
  getSoundVolume(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{gameId}/video/setting */
  getVideoSetting(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{gameId}/audio/voice-volume */
  getVoiceVolume(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/shared-inventory/{itemId}/has */
  hasItem(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/areas/jump */
  jumpToArea(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/levels/{level}/jump */
  jumpToLevel(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/levels/{level}/jump-to-point */
  jumpToPointInLevel(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/areas/load */
  loadArea(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/load */
  loadGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/games/{id}/version/{version} */
  loadGameVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/levels/{level}/load */
  loadLevel(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{id}/publish */
  publishGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/games/shared-inventory/{itemId} */
  removeItemFromInventory(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{id}/republish */
  republishGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/audio/master-volume */
  setMasterVolume(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/audio/sound-volume */
  setSoundVolume(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/video/setting */
  setVideoSetting(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/audio/voice-volume */
  setVoiceVolume(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/ui/credits */
  showCredits(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/ui/main-menu */
  showMainMenu(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/ui/options */
  showOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/ui/title-screen */
  showTitleScreen(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/start */
  startGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/areas/{areaId}/unload */
  unloadArea(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/unload */
  unloadGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/games/{gameId}/levels/{level}/unload */
  unloadLevel(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/games/{id} */
  updateGame(args?: Record<string, any>): Promise<OASISResponse>;
}
