'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/geoHotSpots (source: STAR WebAPI GeoHotSpotsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class GeoHotSpotsModule {
  constructor(http) {
    this._http = http;

    // post api/geoHotSpots/{id}/activate
    this.activateGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/activate");
    // post api/geoHotSpots/
    this.createGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "");
    // post api/geoHotSpots/create
    this.createGeoHotSpotWithOptions = makeOperation(http, "api/geoHotSpots", "POST", "create");
    // post api/geoHotSpots/{id}/deactivate
    this.deactivateGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/deactivate");
    // delete api/geoHotSpots/{id}
    this.deleteGeoHotSpot = makeOperation(http, "api/geoHotSpots", "DELETE", "{id}");
    // post api/geoHotSpots/{id}/download
    this.downloadGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/download");
    // post api/geoHotSpots/{id}/edit
    this.editGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/edit");
    // get api/geoHotSpots/
    this.getAllGeoHotSpots = makeOperation(http, "api/geoHotSpots", "GET", "");
    // get api/geoHotSpots/{id}
    this.getGeoHotSpot = makeOperation(http, "api/geoHotSpots", "GET", "{id}");
    // get api/geoHotSpots/{id}/versions
    this.getGeoHotSpotVersions = makeOperation(http, "api/geoHotSpots", "GET", "{id}/versions");
    // get api/geoHotSpots/nearby
    this.getNearbyGeoHotSpots = makeOperation(http, "api/geoHotSpots", "GET", "nearby");
    // get api/geoHotSpots/load-all-for-avatar
    this.loadAllGeoHotSpotsForAvatar = makeOperation(http, "api/geoHotSpots", "GET", "load-all-for-avatar");
    // get api/geoHotSpots/{id}/load
    this.loadGeoHotSpot = makeOperation(http, "api/geoHotSpots", "GET", "{id}/load");
    // get api/geoHotSpots/load-from-path
    this.loadGeoHotSpotFromPath = makeOperation(http, "api/geoHotSpots", "GET", "load-from-path");
    // get api/geoHotSpots/load-from-published
    this.loadGeoHotSpotFromPublished = makeOperation(http, "api/geoHotSpots", "GET", "load-from-published");
    // get api/geoHotSpots/{id}/version/{version}
    this.loadGeoHotSpotVersion = makeOperation(http, "api/geoHotSpots", "GET", "{id}/version/{version}");
    // post api/geoHotSpots/{id}/publish
    this.publishGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/publish");
    // post api/geoHotSpots/{id}/republish
    this.republishGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/republish");
    // post api/geoHotSpots/{id}/unpublish
    this.unpublishGeoHotSpot = makeOperation(http, "api/geoHotSpots", "POST", "{id}/unpublish");
    // put api/geoHotSpots/{id}
    this.updateGeoHotSpot = makeOperation(http, "api/geoHotSpots", "PUT", "{id}");
  }
}

module.exports = { GeoHotSpotsModule };
