// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class GeoHotSpotsModule {
  constructor(http: unknown);

  /** POST api/geoHotSpots/ */
  createGeoHotSpot(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoHotSpots/create */
  createGeoHotSpotWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/geoHotSpots/{id} */
  deleteGeoHotSpot(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoHotSpots/{id}/edit */
  editGeoHotSpot(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoHotSpots/ */
  getAllGeoHotSpots(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoHotSpots/{id} */
  getGeoHotSpot(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoHotSpots/{id}/versions */
  getGeoHotSpotVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoHotSpots/{id}/version/{version} */
  loadGeoHotSpotVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoHotSpots/{id}/publish */
  publishGeoHotSpot(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/geoHotSpots/{id} */
  updateGeoHotSpot(args?: Record<string, any>): Promise<OASISResponse>;
}
