'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/geoNFTs (source: STAR WebAPI GeoNFTsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class GeoNFTsModule {
  constructor(http) {
    this._http = http;

    // POST api/geoNFTs/{id}/activate (query: version)
    this.activateGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/activate", {"query":["version"]});
    // POST api/geoNFTs/
    this.createGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "");
    // POST api/geoNFTs/create
    this.createGeoNFTWithOptions = makeOperation(http, "api/geoNFTs", "POST", "create");
    // POST api/geoNFTs/{id}/deactivate (query: version)
    this.deactivateGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/geoNFTs/{id}
    this.deleteGeoNFT = makeOperation(http, "api/geoNFTs", "DELETE", "{id}");
    // POST api/geoNFTs/{id}/download (query: version, downloadPath, reInstall)
    this.downloadGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/geoNFTs/{id}/edit
    this.editGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/edit");
    // GET api/geoNFTs/
    this.getAllGeoNFTs = makeOperation(http, "api/geoNFTs", "GET", "");
    // GET api/geoNFTs/{id}
    this.getGeoNFT = makeOperation(http, "api/geoNFTs", "GET", "{id}");
    // GET api/geoNFTs/{id}/versions
    this.getGeoNFTVersions = makeOperation(http, "api/geoNFTs", "GET", "{id}/versions");
    // GET api/geoNFTs/by-avatar/{avatarId}
    this.getGeoNFTsByAvatar = makeOperation(http, "api/geoNFTs", "GET", "by-avatar/{avatarId}");
    // GET api/geoNFTs/nearby (query: latitude, longitude, radiusKm)
    this.getNearbyGeoNFTs = makeOperation(http, "api/geoNFTs", "GET", "nearby", {"query":["latitude","longitude","radiusKm"]});
    // GET api/geoNFTs/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllGeoNFTsForAvatar = makeOperation(http, "api/geoNFTs", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/geoNFTs/{id}/load (query: version, holonType)
    this.loadGeoNFT = makeOperation(http, "api/geoNFTs", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/geoNFTs/load-from-path (query: path, holonType)
    this.loadGeoNFTFromPath = makeOperation(http, "api/geoNFTs", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/geoNFTs/load-from-published (query: publishedFilePath)
    this.loadGeoNFTFromPublished = makeOperation(http, "api/geoNFTs", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/geoNFTs/{id}/version/{version}
    this.loadGeoNFTVersion = makeOperation(http, "api/geoNFTs", "GET", "{id}/version/{version}");
    // POST api/geoNFTs/{id}/publish
    this.publishGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/publish");
    // POST api/geoNFTs/{id}/republish (query: version)
    this.republishGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/republish", {"query":["version"]});
    // GET api/geoNFTs/search (query: query)
    this.searchGeoNFTs = makeOperation(http, "api/geoNFTs", "GET", "search", {"query":["query"]});
    // POST api/geoNFTs/{id}/unpublish (query: version)
    this.unpublishGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/geoNFTs/{id}
    this.updateGeoNFT = makeOperation(http, "api/geoNFTs", "PUT", "{id}");
  }
}

module.exports = { GeoNFTsModule };
