// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class GeoNFTsModule {
  constructor(http: unknown);

  /** POST api/geoNFTs/{id}/activate */
  activateGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/ */
  createGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/create */
  createGeoNFTWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/{id}/deactivate */
  deactivateGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/geoNFTs/{id} */
  deleteGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/{id}/download */
  downloadGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/{id}/edit */
  editGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/ */
  getAllGeoNFTs(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/{id} */
  getGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/by-avatar/{avatarId} */
  getGeoNFTsByAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/{id}/versions */
  getGeoNFTVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/nearby */
  getNearbyGeoNFTs(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/load-all-for-avatar */
  loadAllGeoNFTsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/{id}/load */
  loadGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/load-from-path */
  loadGeoNFTFromPath(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/load-from-published */
  loadGeoNFTFromPublished(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/{id}/version/{version} */
  loadGeoNFTVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/{id}/publish */
  publishGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/{id}/republish */
  republishGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/geoNFTs/search */
  searchGeoNFTs(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/geoNFTs/{id}/unpublish */
  unpublishGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/geoNFTs/{id} */
  updateGeoNFT(args?: Record<string, any>): Promise<OASISResponse>;
}
