'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/geoNFTs (source: STAR WebAPI GeoNFTsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class GeoNFTsModule {
  constructor(http) {
    this._http = http;

    // post api/geoNFTs/{id}/activate
    this.activateGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/activate");
    // post api/geoNFTs/
    this.createGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "");
    // post api/geoNFTs/create
    this.createGeoNFTWithOptions = makeOperation(http, "api/geoNFTs", "POST", "create");
    // post api/geoNFTs/{id}/deactivate
    this.deactivateGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/deactivate");
    // delete api/geoNFTs/{id}
    this.deleteGeoNFT = makeOperation(http, "api/geoNFTs", "DELETE", "{id}");
    // post api/geoNFTs/{id}/download
    this.downloadGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/download");
    // post api/geoNFTs/{id}/edit
    this.editGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/edit");
    // get api/geoNFTs/
    this.getAllGeoNFTs = makeOperation(http, "api/geoNFTs", "GET", "");
    // get api/geoNFTs/{id}
    this.getGeoNFT = makeOperation(http, "api/geoNFTs", "GET", "{id}");
    // get api/geoNFTs/{id}/versions
    this.getGeoNFTVersions = makeOperation(http, "api/geoNFTs", "GET", "{id}/versions");
    // get api/geoNFTs/by-avatar/{avatarId}
    this.getGeoNFTsByAvatar = makeOperation(http, "api/geoNFTs", "GET", "by-avatar/{avatarId}");
    // get api/geoNFTs/nearby
    this.getNearbyGeoNFTs = makeOperation(http, "api/geoNFTs", "GET", "nearby");
    // get api/geoNFTs/load-all-for-avatar
    this.loadAllGeoNFTsForAvatar = makeOperation(http, "api/geoNFTs", "GET", "load-all-for-avatar");
    // get api/geoNFTs/{id}/load
    this.loadGeoNFT = makeOperation(http, "api/geoNFTs", "GET", "{id}/load");
    // get api/geoNFTs/load-from-path
    this.loadGeoNFTFromPath = makeOperation(http, "api/geoNFTs", "GET", "load-from-path");
    // get api/geoNFTs/load-from-published
    this.loadGeoNFTFromPublished = makeOperation(http, "api/geoNFTs", "GET", "load-from-published");
    // get api/geoNFTs/{id}/version/{version}
    this.loadGeoNFTVersion = makeOperation(http, "api/geoNFTs", "GET", "{id}/version/{version}");
    // post api/geoNFTs/{id}/publish
    this.publishGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/publish");
    // post api/geoNFTs/{id}/republish
    this.republishGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/republish");
    // get api/geoNFTs/search
    this.searchGeoNFTs = makeOperation(http, "api/geoNFTs", "GET", "search");
    // post api/geoNFTs/{id}/unpublish
    this.unpublishGeoNFT = makeOperation(http, "api/geoNFTs", "POST", "{id}/unpublish");
    // put api/geoNFTs/{id}
    this.updateGeoNFT = makeOperation(http, "api/geoNFTs", "PUT", "{id}");
  }
}

module.exports = { GeoNFTsModule };
