// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HealthModule {
  constructor(http: unknown);

  /** GET api/health/ */
  get(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/health/health */
  health(args?: Record<string, any>): Promise<OASISResponse>;
}
