'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/health (source: STAR WebAPI HealthController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HealthModule {
  constructor(http) {
    this._http = http;

    // get api/health/
    this.get = makeOperation(http, "api/health", "GET", "");
    // get api/health/health
    this.health = makeOperation(http, "api/health", "GET", "health");
  }
}

module.exports = { HealthModule };
