// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HolonsMetaDataModule {
  constructor(http: unknown);

  /** POST api/holonsMetaData/{id}/activate */
  activateHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/{id}/clone */
  cloneHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/ */
  createHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/create */
  createHolonMetaDataWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/{id}/deactivate */
  deactivateHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/holonsMetaData/{id} */
  deleteHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/{id}/download */
  downloadHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/holonsMetaData/{id}/edit */
  editHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/ */
  getAllHolonsMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/{id} */
  getHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/{id}/versions */
  getHolonMetaDataVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/load-all-for-avatar */
  loadAllHolonMetaDataForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/load-from-path */
  loadHolonMetaDataFromPath(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/load-from-published */
  loadHolonMetaDataFromPublished(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/{id}/versions/{version} */
  loadHolonMetaDataVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/{id}/publish */
  publishHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/{id}/republish */
  republishHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holonsMetaData/search */
  searchHolonsMetaDataGet(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/search */
  searchHolonsMetaDataPost(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holonsMetaData/{id}/unpublish */
  unpublishHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/holonsMetaData/{id} */
  updateHolonMetaData(args?: Record<string, any>): Promise<OASISResponse>;
}
