'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/holons (source: STAR WebAPI HolonsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolonsModule {
  constructor(http) {
    this._http = http;

    // POST api/holons/{id}/activate (query: version)
    this.activateHolon = makeOperation(http, "api/holons", "POST", "{id}/activate", {"query":["version"]});
    // POST api/holons/
    this.createHolon = makeOperation(http, "api/holons", "POST", "");
    // POST api/holons/create
    this.createHolonWithOptions = makeOperation(http, "api/holons", "POST", "create");
    // POST api/holons/{id}/deactivate (query: version)
    this.deactivateHolon = makeOperation(http, "api/holons", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/holons/{id}
    this.deleteHolon = makeOperation(http, "api/holons", "DELETE", "{id}");
    // POST api/holons/{id}/download (query: version, downloadPath, reInstall)
    this.downloadHolon = makeOperation(http, "api/holons", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/holons/{id}/edit
    this.editHolon = makeOperation(http, "api/holons", "POST", "{id}/edit");
    // GET api/holons/
    this.getAllHolons = makeOperation(http, "api/holons", "GET", "");
    // GET api/holons/{id}
    this.getHolon = makeOperation(http, "api/holons", "GET", "{id}");
    // GET api/holons/{id}/versions
    this.getHolonVersions = makeOperation(http, "api/holons", "GET", "{id}/versions");
    // GET api/holons/by-metadata (query: key, value)
    this.getHolonsByMetadata = makeOperation(http, "api/holons", "GET", "by-metadata", {"query":["key","value"]});
    // GET api/holons/by-parent/{parentId}
    this.getHolonsByParent = makeOperation(http, "api/holons", "GET", "by-parent/{parentId}");
    // GET api/holons/by-status/{status}
    this.getHolonsByStatus = makeOperation(http, "api/holons", "GET", "by-status/{status}");
    // GET api/holons/by-type/{type}
    this.getHolonsByType = makeOperation(http, "api/holons", "GET", "by-type/{type}");
    // GET api/holons/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllHolonsForAvatar = makeOperation(http, "api/holons", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/holons/{id}/load (query: version, holonType)
    this.loadHolon = makeOperation(http, "api/holons", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/holons/load-from-path (query: path, holonType)
    this.loadHolonFromPath = makeOperation(http, "api/holons", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/holons/load-from-published (query: publishedFilePath)
    this.loadHolonFromPublished = makeOperation(http, "api/holons", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/holons/{id}/version/{version}
    this.loadHolonVersion = makeOperation(http, "api/holons", "GET", "{id}/version/{version}");
    // POST api/holons/{id}/publish
    this.publishHolon = makeOperation(http, "api/holons", "POST", "{id}/publish");
    // POST api/holons/{id}/republish (query: version)
    this.republishHolon = makeOperation(http, "api/holons", "POST", "{id}/republish", {"query":["version"]});
    // GET api/holons/search (query: query)
    this.searchHolons = makeOperation(http, "api/holons", "GET", "search", {"query":["query"]});
    // POST api/holons/{id}/unpublish (query: version)
    this.unpublishHolon = makeOperation(http, "api/holons", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/holons/{id}
    this.updateHolon = makeOperation(http, "api/holons", "PUT", "{id}");
  }
}

module.exports = { HolonsModule };
