'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/holons (source: STAR WebAPI HolonsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolonsModule {
  constructor(http) {
    this._http = http;

    // post api/holons/{id}/activate
    this.activateHolon = makeOperation(http, "api/holons", "POST", "{id}/activate");
    // post api/holons/
    this.createHolon = makeOperation(http, "api/holons", "POST", "");
    // post api/holons/create
    this.createHolonWithOptions = makeOperation(http, "api/holons", "POST", "create");
    // post api/holons/{id}/deactivate
    this.deactivateHolon = makeOperation(http, "api/holons", "POST", "{id}/deactivate");
    // delete api/holons/{id}
    this.deleteHolon = makeOperation(http, "api/holons", "DELETE", "{id}");
    // post api/holons/{id}/download
    this.downloadHolon = makeOperation(http, "api/holons", "POST", "{id}/download");
    // post api/holons/{id}/edit
    this.editHolon = makeOperation(http, "api/holons", "POST", "{id}/edit");
    // get api/holons/
    this.getAllHolons = makeOperation(http, "api/holons", "GET", "");
    // get api/holons/{id}
    this.getHolon = makeOperation(http, "api/holons", "GET", "{id}");
    // get api/holons/{id}/versions
    this.getHolonVersions = makeOperation(http, "api/holons", "GET", "{id}/versions");
    // get api/holons/by-metadata
    this.getHolonsByMetadata = makeOperation(http, "api/holons", "GET", "by-metadata");
    // get api/holons/by-parent/{parentId}
    this.getHolonsByParent = makeOperation(http, "api/holons", "GET", "by-parent/{parentId}");
    // get api/holons/by-status/{status}
    this.getHolonsByStatus = makeOperation(http, "api/holons", "GET", "by-status/{status}");
    // get api/holons/by-type/{type}
    this.getHolonsByType = makeOperation(http, "api/holons", "GET", "by-type/{type}");
    // get api/holons/load-all-for-avatar
    this.loadAllHolonsForAvatar = makeOperation(http, "api/holons", "GET", "load-all-for-avatar");
    // get api/holons/{id}/load
    this.loadHolon = makeOperation(http, "api/holons", "GET", "{id}/load");
    // get api/holons/load-from-path
    this.loadHolonFromPath = makeOperation(http, "api/holons", "GET", "load-from-path");
    // get api/holons/load-from-published
    this.loadHolonFromPublished = makeOperation(http, "api/holons", "GET", "load-from-published");
    // get api/holons/{id}/version/{version}
    this.loadHolonVersion = makeOperation(http, "api/holons", "GET", "{id}/version/{version}");
    // post api/holons/{id}/publish
    this.publishHolon = makeOperation(http, "api/holons", "POST", "{id}/publish");
    // post api/holons/{id}/republish
    this.republishHolon = makeOperation(http, "api/holons", "POST", "{id}/republish");
    // get api/holons/search
    this.searchHolons = makeOperation(http, "api/holons", "GET", "search");
    // post api/holons/{id}/unpublish
    this.unpublishHolon = makeOperation(http, "api/holons", "POST", "{id}/unpublish");
    // put api/holons/{id}
    this.updateHolon = makeOperation(http, "api/holons", "PUT", "{id}");
  }
}

module.exports = { HolonsModule };
