// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class HolonsModule {
  constructor(http: unknown);

  /** POST api/holons/ */
  createHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holons/create */
  createHolonWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/holons/{id} */
  deleteHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holons/{id}/edit */
  editHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/ */
  getAllHolons(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/{id} */
  getHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/by-parent/{parentId} */
  getHolonsByParent(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/by-status/{status} */
  getHolonsByStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/by-type/{type} */
  getHolonsByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/{id}/versions */
  getHolonVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/holons/{id}/version/{version} */
  loadHolonVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/holons/{id}/publish */
  publishHolon(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/holons/{id} */
  updateHolon(args?: Record<string, any>): Promise<OASISResponse>;
}
