'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/holonsMetaData (source: STAR WebAPI HolonsMetaDataController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolonsMetaDataModule {
  constructor(http) {
    this._http = http;

    // POST api/holonsMetaData/{id}/activate (query: version)
    this.activateHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/activate", {"query":["version"]});
    // POST api/holonsMetaData/{id}/clone
    this.cloneHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/clone");
    // POST api/holonsMetaData/
    this.createHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "");
    // POST api/holonsMetaData/create
    this.createHolonMetaDataWithOptions = makeOperation(http, "api/holonsMetaData", "POST", "create");
    // POST api/holonsMetaData/{id}/deactivate (query: version)
    this.deactivateHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/holonsMetaData/{id}
    this.deleteHolonMetaData = makeOperation(http, "api/holonsMetaData", "DELETE", "{id}");
    // POST api/holonsMetaData/{id}/download
    this.downloadHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/download");
    // PUT api/holonsMetaData/{id}/edit
    this.editHolonMetaData = makeOperation(http, "api/holonsMetaData", "PUT", "{id}/edit");
    // GET api/holonsMetaData/
    this.getAllHolonsMetaData = makeOperation(http, "api/holonsMetaData", "GET", "");
    // GET api/holonsMetaData/{id}
    this.getHolonMetaData = makeOperation(http, "api/holonsMetaData", "GET", "{id}");
    // GET api/holonsMetaData/{id}/versions
    this.getHolonMetaDataVersions = makeOperation(http, "api/holonsMetaData", "GET", "{id}/versions");
    // GET api/holonsMetaData/load-all-for-avatar
    this.loadAllHolonMetaDataForAvatar = makeOperation(http, "api/holonsMetaData", "GET", "load-all-for-avatar");
    // GET api/holonsMetaData/load-from-path (query: path)
    this.loadHolonMetaDataFromPath = makeOperation(http, "api/holonsMetaData", "GET", "load-from-path", {"query":["path"]});
    // GET api/holonsMetaData/load-from-published (query: publishedFilePath)
    this.loadHolonMetaDataFromPublished = makeOperation(http, "api/holonsMetaData", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/holonsMetaData/{id}/versions/{version}
    this.loadHolonMetaDataVersion = makeOperation(http, "api/holonsMetaData", "GET", "{id}/versions/{version}");
    // POST api/holonsMetaData/{id}/publish
    this.publishHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/publish");
    // POST api/holonsMetaData/{id}/republish (query: version)
    this.republishHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/republish", {"query":["version"]});
    // POST api/holonsMetaData/search
    this.searchHolonsMetaData = makeOperation(http, "api/holonsMetaData", "POST", "search");
    // POST api/holonsMetaData/{id}/unpublish (query: version)
    this.unpublishHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/holonsMetaData/{id}
    this.updateHolonMetaData = makeOperation(http, "api/holonsMetaData", "PUT", "{id}");
  }
}

module.exports = { HolonsMetaDataModule };
