'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/holonsMetaData (source: STAR WebAPI HolonsMetaDataController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class HolonsMetaDataModule {
  constructor(http) {
    this._http = http;

    // post api/holonsMetaData/{id}/activate
    this.activateHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/activate");
    // post api/holonsMetaData/{id}/clone
    this.cloneHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/clone");
    // post api/holonsMetaData/
    this.createHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "");
    // post api/holonsMetaData/create
    this.createHolonMetaDataWithOptions = makeOperation(http, "api/holonsMetaData", "POST", "create");
    // post api/holonsMetaData/{id}/deactivate
    this.deactivateHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/deactivate");
    // delete api/holonsMetaData/{id}
    this.deleteHolonMetaData = makeOperation(http, "api/holonsMetaData", "DELETE", "{id}");
    // post api/holonsMetaData/{id}/download
    this.downloadHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/download");
    // put api/holonsMetaData/{id}/edit
    this.editHolonMetaData = makeOperation(http, "api/holonsMetaData", "PUT", "{id}/edit");
    // get api/holonsMetaData/
    this.getAllHolonsMetaData = makeOperation(http, "api/holonsMetaData", "GET", "");
    // get api/holonsMetaData/{id}
    this.getHolonMetaData = makeOperation(http, "api/holonsMetaData", "GET", "{id}");
    // get api/holonsMetaData/{id}/versions
    this.getHolonMetaDataVersions = makeOperation(http, "api/holonsMetaData", "GET", "{id}/versions");
    // get api/holonsMetaData/load-all-for-avatar
    this.loadAllHolonMetaDataForAvatar = makeOperation(http, "api/holonsMetaData", "GET", "load-all-for-avatar");
    // get api/holonsMetaData/load-from-path
    this.loadHolonMetaDataFromPath = makeOperation(http, "api/holonsMetaData", "GET", "load-from-path");
    // get api/holonsMetaData/load-from-published
    this.loadHolonMetaDataFromPublished = makeOperation(http, "api/holonsMetaData", "GET", "load-from-published");
    // get api/holonsMetaData/{id}/versions/{version}
    this.loadHolonMetaDataVersion = makeOperation(http, "api/holonsMetaData", "GET", "{id}/versions/{version}");
    // post api/holonsMetaData/{id}/publish
    this.publishHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/publish");
    // post api/holonsMetaData/{id}/republish
    this.republishHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/republish");
    // get api/holonsMetaData/search
    this.searchHolonsMetaDataGet = makeOperation(http, "api/holonsMetaData", "GET", "search");
    // post api/holonsMetaData/search
    this.searchHolonsMetaDataPost = makeOperation(http, "api/holonsMetaData", "POST", "search");
    // post api/holonsMetaData/{id}/unpublish
    this.unpublishHolonMetaData = makeOperation(http, "api/holonsMetaData", "POST", "{id}/unpublish");
    // put api/holonsMetaData/{id}
    this.updateHolonMetaData = makeOperation(http, "api/holonsMetaData", "PUT", "{id}");
  }
}

module.exports = { HolonsMetaDataModule };
