'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { AvatarModule } = require('./Avatar');
const { CelestialBodiesModule } = require('./CelestialBodies');
const { CelestialBodiesMetaDataModule } = require('./CelestialBodiesMetaData');
const { CelestialSpacesModule } = require('./CelestialSpaces');
const { ChaptersModule } = require('./Chapters');
const { CompetitionModule } = require('./Competition');
const { CosmicModule } = require('./Cosmic');
const { GamesModule } = require('./Games');
const { GeoHotSpotsModule } = require('./GeoHotSpots');
const { GeoNFTsModule } = require('./GeoNFTs');
const { HealthModule } = require('./Health');
const { HolonsModule } = require('./Holons');
const { HolonsMetaDataModule } = require('./HolonsMetaData');
const { InventoryItemsModule } = require('./InventoryItems');
const { LibrariesModule } = require('./Libraries');
const { MissionsModule } = require('./Missions');
const { NFTsModule } = require('./NFTs');
const { OAPPsModule } = require('./OAPPs');
const { ParksModule } = require('./Parks');
const { PluginsModule } = require('./Plugins');
const { QuestsModule } = require('./Quests');
const { RuntimesModule } = require('./Runtimes');
const { STARModule } = require('./STAR');
const { TemplatesModule } = require('./Templates');
const { ZomesModule } = require('./Zomes');
const { ZomesMetaDataModule } = require('./ZomesMetaData');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.quests, client.nFTs, client.cosmic). Hand-written ergonomic
 * modules (auth/avatar) are attached separately in src/index.js and take
 * precedence where names overlap.
 */
function attachGeneratedModules(client, http) {
  client.avatar = client.avatar || new AvatarModule(http);
  client.celestialBodies = client.celestialBodies || new CelestialBodiesModule(http);
  client.celestialBodiesMetaData = client.celestialBodiesMetaData || new CelestialBodiesMetaDataModule(http);
  client.celestialSpaces = client.celestialSpaces || new CelestialSpacesModule(http);
  client.chapters = client.chapters || new ChaptersModule(http);
  client.competition = client.competition || new CompetitionModule(http);
  client.cosmic = client.cosmic || new CosmicModule(http);
  client.games = client.games || new GamesModule(http);
  client.geoHotSpots = client.geoHotSpots || new GeoHotSpotsModule(http);
  client.geoNFTs = client.geoNFTs || new GeoNFTsModule(http);
  client.health = client.health || new HealthModule(http);
  client.holons = client.holons || new HolonsModule(http);
  client.holonsMetaData = client.holonsMetaData || new HolonsMetaDataModule(http);
  client.inventoryItems = client.inventoryItems || new InventoryItemsModule(http);
  client.libraries = client.libraries || new LibrariesModule(http);
  client.missions = client.missions || new MissionsModule(http);
  client.nFTs = client.nFTs || new NFTsModule(http);
  client.oAPPs = client.oAPPs || new OAPPsModule(http);
  client.parks = client.parks || new ParksModule(http);
  client.plugins = client.plugins || new PluginsModule(http);
  client.quests = client.quests || new QuestsModule(http);
  client.runtimes = client.runtimes || new RuntimesModule(http);
  client.sTAR = client.sTAR || new STARModule(http);
  client.templates = client.templates || new TemplatesModule(http);
  client.zomes = client.zomes || new ZomesModule(http);
  client.zomesMetaData = client.zomesMetaData || new ZomesMetaDataModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
