'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/inventoryItems (source: STAR WebAPI InventoryItemsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class InventoryItemsModule {
  constructor(http) {
    this._http = http;

    // post api/inventoryItems/{id}/activate
    this.activateInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/activate");
    // post api/inventoryItems/
    this.createInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "");
    // post api/inventoryItems/create
    this.createInventoryItemWithOptions = makeOperation(http, "api/inventoryItems", "POST", "create");
    // post api/inventoryItems/{id}/deactivate
    this.deactivateInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/deactivate");
    // delete api/inventoryItems/{id}
    this.deleteInventoryItem = makeOperation(http, "api/inventoryItems", "DELETE", "{id}");
    // post api/inventoryItems/{id}/download
    this.downloadInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/download");
    // post api/inventoryItems/{id}/edit
    this.editInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/edit");
    // get api/inventoryItems/
    this.getAllInventoryItems = makeOperation(http, "api/inventoryItems", "GET", "");
    // get api/inventoryItems/{id}
    this.getInventoryItem = makeOperation(http, "api/inventoryItems", "GET", "{id}");
    // get api/inventoryItems/{id}/versions
    this.getInventoryItemVersions = makeOperation(http, "api/inventoryItems", "GET", "{id}/versions");
    // get api/inventoryItems/by-avatar/{avatarId}
    this.getInventoryItemsByAvatar = makeOperation(http, "api/inventoryItems", "GET", "by-avatar/{avatarId}");
    // get api/inventoryItems/load-all-for-avatar
    this.loadAllInventoryItemsForAvatar = makeOperation(http, "api/inventoryItems", "GET", "load-all-for-avatar");
    // get api/inventoryItems/{id}/load
    this.loadInventoryItem = makeOperation(http, "api/inventoryItems", "GET", "{id}/load");
    // get api/inventoryItems/load-from-path
    this.loadInventoryItemFromPath = makeOperation(http, "api/inventoryItems", "GET", "load-from-path");
    // get api/inventoryItems/load-from-published
    this.loadInventoryItemFromPublished = makeOperation(http, "api/inventoryItems", "GET", "load-from-published");
    // get api/inventoryItems/{id}/version/{version}
    this.loadInventoryItemVersion = makeOperation(http, "api/inventoryItems", "GET", "{id}/version/{version}");
    // post api/inventoryItems/{id}/publish
    this.publishInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/publish");
    // post api/inventoryItems/{id}/republish
    this.republishInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/republish");
    // post api/inventoryItems/search
    this.searchInventoryItems = makeOperation(http, "api/inventoryItems", "POST", "search");
    // post api/inventoryItems/{id}/unpublish
    this.unpublishInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/unpublish");
    // put api/inventoryItems/{id}
    this.updateInventoryItem = makeOperation(http, "api/inventoryItems", "PUT", "{id}");
  }
}

module.exports = { InventoryItemsModule };
