'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/inventoryItems (source: STAR WebAPI InventoryItemsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class InventoryItemsModule {
  constructor(http) {
    this._http = http;

    // POST api/inventoryItems/{id}/activate (query: version)
    this.activateInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/activate", {"query":["version"]});
    // POST api/inventoryItems/
    this.createInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "");
    // POST api/inventoryItems/create
    this.createInventoryItemWithOptions = makeOperation(http, "api/inventoryItems", "POST", "create");
    // POST api/inventoryItems/{id}/deactivate (query: version)
    this.deactivateInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/inventoryItems/{id}
    this.deleteInventoryItem = makeOperation(http, "api/inventoryItems", "DELETE", "{id}");
    // POST api/inventoryItems/{id}/download (query: version, downloadPath, reInstall)
    this.downloadInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/inventoryItems/{id}/edit
    this.editInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/edit");
    // GET api/inventoryItems/
    this.getAllInventoryItems = makeOperation(http, "api/inventoryItems", "GET", "");
    // GET api/inventoryItems/{id}
    this.getInventoryItem = makeOperation(http, "api/inventoryItems", "GET", "{id}");
    // GET api/inventoryItems/{id}/versions
    this.getInventoryItemVersions = makeOperation(http, "api/inventoryItems", "GET", "{id}/versions");
    // GET api/inventoryItems/by-avatar/{avatarId}
    this.getInventoryItemsByAvatar = makeOperation(http, "api/inventoryItems", "GET", "by-avatar/{avatarId}");
    // GET api/inventoryItems/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllInventoryItemsForAvatar = makeOperation(http, "api/inventoryItems", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/inventoryItems/{id}/load (query: version, holonType)
    this.loadInventoryItem = makeOperation(http, "api/inventoryItems", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/inventoryItems/load-from-path (query: path, holonType)
    this.loadInventoryItemFromPath = makeOperation(http, "api/inventoryItems", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/inventoryItems/load-from-published (query: publishedFilePath)
    this.loadInventoryItemFromPublished = makeOperation(http, "api/inventoryItems", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/inventoryItems/{id}/version/{version}
    this.loadInventoryItemVersion = makeOperation(http, "api/inventoryItems", "GET", "{id}/version/{version}");
    // POST api/inventoryItems/{id}/publish
    this.publishInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/publish");
    // POST api/inventoryItems/{id}/republish (query: version)
    this.republishInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/republish", {"query":["version"]});
    // POST api/inventoryItems/search
    this.searchInventoryItems = makeOperation(http, "api/inventoryItems", "POST", "search");
    // POST api/inventoryItems/{id}/unpublish (query: version)
    this.unpublishInventoryItem = makeOperation(http, "api/inventoryItems", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/inventoryItems/{id}
    this.updateInventoryItem = makeOperation(http, "api/inventoryItems", "PUT", "{id}");
  }
}

module.exports = { InventoryItemsModule };
