'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/libraries (source: STAR WebAPI LibrariesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class LibrariesModule {
  constructor(http) {
    this._http = http;

    // post api/libraries/{id}/activate
    this.activateLibrary = makeOperation(http, "api/libraries", "POST", "{id}/activate");
    // post api/libraries/{id}/clone
    this.cloneLibrary = makeOperation(http, "api/libraries", "POST", "{id}/clone");
    // post api/libraries/
    this.createLibrary = makeOperation(http, "api/libraries", "POST", "");
    // post api/libraries/create
    this.createLibraryWithOptions = makeOperation(http, "api/libraries", "POST", "create");
    // post api/libraries/{id}/deactivate
    this.deactivateLibrary = makeOperation(http, "api/libraries", "POST", "{id}/deactivate");
    // delete api/libraries/{id}
    this.deleteLibrary = makeOperation(http, "api/libraries", "DELETE", "{id}");
    // post api/libraries/{id}/download
    this.downloadLibrary = makeOperation(http, "api/libraries", "POST", "{id}/download");
    // post api/libraries/{id}/edit
    this.editLibrary = makeOperation(http, "api/libraries", "POST", "{id}/edit");
    // get api/libraries/
    this.getAllLibraries = makeOperation(http, "api/libraries", "GET", "");
    // get api/libraries/by-category/{category}
    this.getLibrariesByCategory = makeOperation(http, "api/libraries", "GET", "by-category/{category}");
    // get api/libraries/{id}
    this.getLibrary = makeOperation(http, "api/libraries", "GET", "{id}");
    // get api/libraries/{id}/versions
    this.getLibraryVersions = makeOperation(http, "api/libraries", "GET", "{id}/versions");
    // get api/libraries/load-all-for-avatar
    this.loadAllLibrariesForAvatar = makeOperation(http, "api/libraries", "GET", "load-all-for-avatar");
    // get api/libraries/{id}/load
    this.loadLibrary = makeOperation(http, "api/libraries", "GET", "{id}/load");
    // get api/libraries/load-from-path
    this.loadLibraryFromPath = makeOperation(http, "api/libraries", "GET", "load-from-path");
    // get api/libraries/load-from-published
    this.loadLibraryFromPublished = makeOperation(http, "api/libraries", "GET", "load-from-published");
    // get api/libraries/{id}/version/{version}
    this.loadLibraryVersion = makeOperation(http, "api/libraries", "GET", "{id}/version/{version}");
    // post api/libraries/{id}/publish
    this.publishLibrary = makeOperation(http, "api/libraries", "POST", "{id}/publish");
    // post api/libraries/{id}/republish
    this.republishLibrary = makeOperation(http, "api/libraries", "POST", "{id}/republish");
    // get api/libraries/search
    this.searchLibraries = makeOperation(http, "api/libraries", "GET", "search");
    // post api/libraries/{id}/unpublish
    this.unpublishLibrary = makeOperation(http, "api/libraries", "POST", "{id}/unpublish");
    // put api/libraries/{id}
    this.updateLibrary = makeOperation(http, "api/libraries", "PUT", "{id}");
  }
}

module.exports = { LibrariesModule };
