'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/nFTs (source: STAR WebAPI NFTsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class NFTsModule {
  constructor(http) {
    this._http = http;

    // post api/nFTs/{id}/activate
    this.activateNFT = makeOperation(http, "api/nFTs", "POST", "{id}/activate");
    // post api/nFTs/{id}/clone
    this.cloneNFT = makeOperation(http, "api/nFTs", "POST", "{id}/clone");
    // post api/nFTs/
    this.createNFT = makeOperation(http, "api/nFTs", "POST", "");
    // post api/nFTs/create
    this.createNFTWithOptions = makeOperation(http, "api/nFTs", "POST", "create");
    // post api/nFTs/{id}/deactivate
    this.deactivateNFT = makeOperation(http, "api/nFTs", "POST", "{id}/deactivate");
    // delete api/nFTs/{id}
    this.deleteNFT = makeOperation(http, "api/nFTs", "DELETE", "{id}");
    // post api/nFTs/{id}/download
    this.downloadNFT = makeOperation(http, "api/nFTs", "POST", "{id}/download");
    // post api/nFTs/{id}/edit
    this.editNFT = makeOperation(http, "api/nFTs", "POST", "{id}/edit");
    // get api/nFTs/
    this.getAllNFTs = makeOperation(http, "api/nFTs", "GET", "");
    // get api/nFTs/{id}
    this.getNFT = makeOperation(http, "api/nFTs", "GET", "{id}");
    // get api/nFTs/{id}/versions
    this.getNFTVersions = makeOperation(http, "api/nFTs", "GET", "{id}/versions");
    // get api/nFTs/load-all-for-avatar
    this.loadAllNFTsForAvatar = makeOperation(http, "api/nFTs", "GET", "load-all-for-avatar");
    // get api/nFTs/{id}/load
    this.loadNFT = makeOperation(http, "api/nFTs", "GET", "{id}/load");
    // get api/nFTs/load-from-path
    this.loadNFTFromPath = makeOperation(http, "api/nFTs", "GET", "load-from-path");
    // get api/nFTs/load-from-published
    this.loadNFTFromPublished = makeOperation(http, "api/nFTs", "GET", "load-from-published");
    // get api/nFTs/{id}/version/{version}
    this.loadNFTVersion = makeOperation(http, "api/nFTs", "GET", "{id}/version/{version}");
    // post api/nFTs/{id}/publish
    this.publishNFT = makeOperation(http, "api/nFTs", "POST", "{id}/publish");
    // post api/nFTs/{id}/republish
    this.republishNFT = makeOperation(http, "api/nFTs", "POST", "{id}/republish");
    // get api/nFTs/search
    this.searchNFTs = makeOperation(http, "api/nFTs", "GET", "search");
    // post api/nFTs/{id}/unpublish
    this.unpublishNFT = makeOperation(http, "api/nFTs", "POST", "{id}/unpublish");
    // put api/nFTs/{id}
    this.updateNFT = makeOperation(http, "api/nFTs", "PUT", "{id}");
  }
}

module.exports = { NFTsModule };
