'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/nFTs (source: STAR WebAPI NFTsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class NFTsModule {
  constructor(http) {
    this._http = http;

    // POST api/nFTs/{id}/activate (query: version)
    this.activateNFT = makeOperation(http, "api/nFTs", "POST", "{id}/activate", {"query":["version"]});
    // POST api/nFTs/{id}/clone
    this.cloneNFT = makeOperation(http, "api/nFTs", "POST", "{id}/clone");
    // POST api/nFTs/
    this.createNFT = makeOperation(http, "api/nFTs", "POST", "");
    // POST api/nFTs/create
    this.createNFTWithOptions = makeOperation(http, "api/nFTs", "POST", "create");
    // POST api/nFTs/{id}/deactivate (query: version)
    this.deactivateNFT = makeOperation(http, "api/nFTs", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/nFTs/{id}
    this.deleteNFT = makeOperation(http, "api/nFTs", "DELETE", "{id}");
    // POST api/nFTs/{id}/download (query: version, downloadPath, reInstall)
    this.downloadNFT = makeOperation(http, "api/nFTs", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/nFTs/{id}/edit
    this.editNFT = makeOperation(http, "api/nFTs", "POST", "{id}/edit");
    // GET api/nFTs/
    this.getAllNFTs = makeOperation(http, "api/nFTs", "GET", "");
    // GET api/nFTs/{id}
    this.getNFT = makeOperation(http, "api/nFTs", "GET", "{id}");
    // GET api/nFTs/{id}/versions
    this.getNFTVersions = makeOperation(http, "api/nFTs", "GET", "{id}/versions");
    // GET api/nFTs/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllNFTsForAvatar = makeOperation(http, "api/nFTs", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/nFTs/{id}/load (query: version, holonType)
    this.loadNFT = makeOperation(http, "api/nFTs", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/nFTs/load-from-path (query: path, holonType)
    this.loadNFTFromPath = makeOperation(http, "api/nFTs", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/nFTs/load-from-published (query: publishedFilePath)
    this.loadNFTFromPublished = makeOperation(http, "api/nFTs", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/nFTs/{id}/version/{version}
    this.loadNFTVersion = makeOperation(http, "api/nFTs", "GET", "{id}/version/{version}");
    // POST api/nFTs/{id}/publish
    this.publishNFT = makeOperation(http, "api/nFTs", "POST", "{id}/publish");
    // POST api/nFTs/{id}/republish (query: version)
    this.republishNFT = makeOperation(http, "api/nFTs", "POST", "{id}/republish", {"query":["version"]});
    // GET api/nFTs/search (query: searchTerm, searchOnlyForCurrentAvatar, showAllVersions, version)
    this.searchNFTs = makeOperation(http, "api/nFTs", "GET", "search", {"query":["searchTerm","searchOnlyForCurrentAvatar","showAllVersions","version"]});
    // POST api/nFTs/{id}/unpublish (query: version)
    this.unpublishNFT = makeOperation(http, "api/nFTs", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/nFTs/{id}
    this.updateNFT = makeOperation(http, "api/nFTs", "PUT", "{id}");
  }
}

module.exports = { NFTsModule };
