// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class OAPPsModule {
  constructor(http: unknown);

  /** POST api/oAPPs/{id}/clone */
  cloneOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oAPPs/ */
  createOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oAPPs/create */
  createOAPPWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/oAPPs/{id} */
  deleteOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oAPPs/{id}/download */
  downloadOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/oAPPs/{id}/edit */
  editOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oAPPs/ */
  getAllOAPPs(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oAPPs/{id} */
  getOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oAPPs/{id}/versions */
  getOAPPVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oAPPs/load-all-for-avatar */
  loadAllOAPPsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/oAPPs/{id}/versions/{version} */
  loadOAPPVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oAPPs/{id}/publish */
  publishOAPP(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/oAPPs/search */
  searchOAPPsPost(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/oAPPs/{id} */
  updateOAPP(args?: Record<string, any>): Promise<OASISResponse>;
}
