'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/oAPPs (source: STAR WebAPI OAPPsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class OAPPsModule {
  constructor(http) {
    this._http = http;

    // POST api/oAPPs/{id}/activate (query: version)
    this.activateOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/activate", {"query":["version"]});
    // POST api/oAPPs/{id}/clone
    this.cloneOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/clone");
    // POST api/oAPPs/
    this.createOAPP = makeOperation(http, "api/oAPPs", "POST", "");
    // POST api/oAPPs/create
    this.createOAPPWithOptions = makeOperation(http, "api/oAPPs", "POST", "create");
    // POST api/oAPPs/{id}/deactivate (query: version)
    this.deactivateOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/oAPPs/{id}
    this.deleteOAPP = makeOperation(http, "api/oAPPs", "DELETE", "{id}");
    // POST api/oAPPs/{id}/download
    this.downloadOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/download");
    // PUT api/oAPPs/{id}/edit
    this.editOAPP = makeOperation(http, "api/oAPPs", "PUT", "{id}/edit");
    // GET api/oAPPs/
    this.getAllOAPPs = makeOperation(http, "api/oAPPs", "GET", "");
    // GET api/oAPPs/{id}
    this.getOAPP = makeOperation(http, "api/oAPPs", "GET", "{id}");
    // GET api/oAPPs/{id}/versions
    this.getOAPPVersions = makeOperation(http, "api/oAPPs", "GET", "{id}/versions");
    // GET api/oAPPs/load-all-for-avatar
    this.loadAllOAPPsForAvatar = makeOperation(http, "api/oAPPs", "GET", "load-all-for-avatar");
    // GET api/oAPPs/load-from-path (query: path)
    this.loadOAPPFromPath = makeOperation(http, "api/oAPPs", "GET", "load-from-path", {"query":["path"]});
    // GET api/oAPPs/load-from-published (query: publishedFilePath)
    this.loadOAPPFromPublished = makeOperation(http, "api/oAPPs", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/oAPPs/{id}/versions/{version}
    this.loadOAPPVersion = makeOperation(http, "api/oAPPs", "GET", "{id}/versions/{version}");
    // POST api/oAPPs/{id}/publish
    this.publishOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/publish");
    // POST api/oAPPs/{id}/republish (query: version)
    this.republishOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/republish", {"query":["version"]});
    // POST api/oAPPs/search
    this.searchOAPPs = makeOperation(http, "api/oAPPs", "POST", "search");
    // POST api/oAPPs/{id}/unpublish (query: version)
    this.unpublishOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/oAPPs/{id}
    this.updateOAPP = makeOperation(http, "api/oAPPs", "PUT", "{id}");
  }
}

module.exports = { OAPPsModule };
