'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/oAPPs (source: STAR WebAPI OAPPsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class OAPPsModule {
  constructor(http) {
    this._http = http;

    // post api/oAPPs/{id}/activate
    this.activateOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/activate");
    // post api/oAPPs/{id}/clone
    this.cloneOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/clone");
    // post api/oAPPs/
    this.createOAPP = makeOperation(http, "api/oAPPs", "POST", "");
    // post api/oAPPs/create
    this.createOAPPWithOptions = makeOperation(http, "api/oAPPs", "POST", "create");
    // post api/oAPPs/{id}/deactivate
    this.deactivateOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/deactivate");
    // delete api/oAPPs/{id}
    this.deleteOAPP = makeOperation(http, "api/oAPPs", "DELETE", "{id}");
    // post api/oAPPs/{id}/download
    this.downloadOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/download");
    // put api/oAPPs/{id}/edit
    this.editOAPP = makeOperation(http, "api/oAPPs", "PUT", "{id}/edit");
    // get api/oAPPs/
    this.getAllOAPPs = makeOperation(http, "api/oAPPs", "GET", "");
    // get api/oAPPs/{id}
    this.getOAPP = makeOperation(http, "api/oAPPs", "GET", "{id}");
    // get api/oAPPs/{id}/versions
    this.getOAPPVersions = makeOperation(http, "api/oAPPs", "GET", "{id}/versions");
    // get api/oAPPs/load-all-for-avatar
    this.loadAllOAPPsForAvatar = makeOperation(http, "api/oAPPs", "GET", "load-all-for-avatar");
    // get api/oAPPs/load-from-path
    this.loadOAPPFromPath = makeOperation(http, "api/oAPPs", "GET", "load-from-path");
    // get api/oAPPs/load-from-published
    this.loadOAPPFromPublished = makeOperation(http, "api/oAPPs", "GET", "load-from-published");
    // get api/oAPPs/{id}/versions/{version}
    this.loadOAPPVersion = makeOperation(http, "api/oAPPs", "GET", "{id}/versions/{version}");
    // post api/oAPPs/{id}/publish
    this.publishOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/publish");
    // post api/oAPPs/{id}/republish
    this.republishOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/republish");
    // get api/oAPPs/search
    this.searchOAPPsGet = makeOperation(http, "api/oAPPs", "GET", "search");
    // post api/oAPPs/search
    this.searchOAPPsPost = makeOperation(http, "api/oAPPs", "POST", "search");
    // post api/oAPPs/{id}/unpublish
    this.unpublishOAPP = makeOperation(http, "api/oAPPs", "POST", "{id}/unpublish");
    // put api/oAPPs/{id}
    this.updateOAPP = makeOperation(http, "api/oAPPs", "PUT", "{id}");
  }
}

module.exports = { OAPPsModule };
