// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ParksModule {
  constructor(http: unknown);

  /** POST api/parks/{id}/activate */
  activatePark(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/ */
  createPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/create */
  createParkWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/{id}/deactivate */
  deactivatePark(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/parks/{id} */
  deletePark(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/{id}/download */
  downloadPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/{id}/edit */
  editPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/ */
  getAllParks(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/nearby */
  getNearbyParks(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/{id} */
  getPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/by-type/{type} */
  getParksByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/{id}/versions */
  getParkVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/load-all-for-avatar */
  loadAllParksForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/{id}/load */
  loadPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/load-from-path */
  loadParkFromPath(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/load-from-published */
  loadParkFromPublished(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/parks/{id}/version/{version} */
  loadParkVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/{id}/publish */
  publishPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/{id}/republish */
  republishPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/search */
  searchParks(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/parks/{id}/unpublish */
  unpublishPark(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/parks/{id} */
  updatePark(args?: Record<string, any>): Promise<OASISResponse>;
}
