'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/parks (source: STAR WebAPI ParksController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ParksModule {
  constructor(http) {
    this._http = http;

    // post api/parks/{id}/activate
    this.activatePark = makeOperation(http, "api/parks", "POST", "{id}/activate");
    // post api/parks/
    this.createPark = makeOperation(http, "api/parks", "POST", "");
    // post api/parks/create
    this.createParkWithOptions = makeOperation(http, "api/parks", "POST", "create");
    // post api/parks/{id}/deactivate
    this.deactivatePark = makeOperation(http, "api/parks", "POST", "{id}/deactivate");
    // delete api/parks/{id}
    this.deletePark = makeOperation(http, "api/parks", "DELETE", "{id}");
    // post api/parks/{id}/download
    this.downloadPark = makeOperation(http, "api/parks", "POST", "{id}/download");
    // post api/parks/{id}/edit
    this.editPark = makeOperation(http, "api/parks", "POST", "{id}/edit");
    // get api/parks/
    this.getAllParks = makeOperation(http, "api/parks", "GET", "");
    // get api/parks/nearby
    this.getNearbyParks = makeOperation(http, "api/parks", "GET", "nearby");
    // get api/parks/{id}
    this.getPark = makeOperation(http, "api/parks", "GET", "{id}");
    // get api/parks/{id}/versions
    this.getParkVersions = makeOperation(http, "api/parks", "GET", "{id}/versions");
    // get api/parks/by-type/{type}
    this.getParksByType = makeOperation(http, "api/parks", "GET", "by-type/{type}");
    // get api/parks/load-all-for-avatar
    this.loadAllParksForAvatar = makeOperation(http, "api/parks", "GET", "load-all-for-avatar");
    // get api/parks/{id}/load
    this.loadPark = makeOperation(http, "api/parks", "GET", "{id}/load");
    // get api/parks/load-from-path
    this.loadParkFromPath = makeOperation(http, "api/parks", "GET", "load-from-path");
    // get api/parks/load-from-published
    this.loadParkFromPublished = makeOperation(http, "api/parks", "GET", "load-from-published");
    // get api/parks/{id}/version/{version}
    this.loadParkVersion = makeOperation(http, "api/parks", "GET", "{id}/version/{version}");
    // post api/parks/{id}/publish
    this.publishPark = makeOperation(http, "api/parks", "POST", "{id}/publish");
    // post api/parks/{id}/republish
    this.republishPark = makeOperation(http, "api/parks", "POST", "{id}/republish");
    // post api/parks/search
    this.searchParks = makeOperation(http, "api/parks", "POST", "search");
    // post api/parks/{id}/unpublish
    this.unpublishPark = makeOperation(http, "api/parks", "POST", "{id}/unpublish");
    // put api/parks/{id}
    this.updatePark = makeOperation(http, "api/parks", "PUT", "{id}");
  }
}

module.exports = { ParksModule };
