'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/plugins (source: STAR WebAPI PluginsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class PluginsModule {
  constructor(http) {
    this._http = http;

    // POST api/plugins/{id}/activate (query: version)
    this.activatePlugin = makeOperation(http, "api/plugins", "POST", "{id}/activate", {"query":["version"]});
    // POST api/plugins/{id}/clone
    this.clonePlugin = makeOperation(http, "api/plugins", "POST", "{id}/clone");
    // POST api/plugins/
    this.createPlugin = makeOperation(http, "api/plugins", "POST", "");
    // POST api/plugins/create
    this.createPluginWithOptions = makeOperation(http, "api/plugins", "POST", "create");
    // POST api/plugins/{id}/deactivate (query: version)
    this.deactivatePlugin = makeOperation(http, "api/plugins", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/plugins/{id}
    this.deletePlugin = makeOperation(http, "api/plugins", "DELETE", "{id}");
    // POST api/plugins/{id}/download (query: version, downloadPath, reInstall)
    this.downloadPlugin = makeOperation(http, "api/plugins", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/plugins/{id}/edit
    this.editPlugin = makeOperation(http, "api/plugins", "POST", "{id}/edit");
    // GET api/plugins/
    this.getAllPlugins = makeOperation(http, "api/plugins", "GET", "");
    // GET api/plugins/{id}
    this.getPlugin = makeOperation(http, "api/plugins", "GET", "{id}");
    // GET api/plugins/{id}/versions
    this.getPluginVersions = makeOperation(http, "api/plugins", "GET", "{id}/versions");
    // GET api/plugins/by-type/{type}
    this.getPluginsByType = makeOperation(http, "api/plugins", "GET", "by-type/{type}");
    // POST api/plugins/{id}/install
    this.installPlugin = makeOperation(http, "api/plugins", "POST", "{id}/install");
    // GET api/plugins/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllPluginsForAvatar = makeOperation(http, "api/plugins", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/plugins/{id}/load (query: version, holonType)
    this.loadPlugin = makeOperation(http, "api/plugins", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/plugins/load-from-path (query: path, holonType)
    this.loadPluginFromPath = makeOperation(http, "api/plugins", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/plugins/load-from-published (query: publishedFilePath)
    this.loadPluginFromPublished = makeOperation(http, "api/plugins", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/plugins/{id}/version/{version}
    this.loadPluginVersion = makeOperation(http, "api/plugins", "GET", "{id}/version/{version}");
    // POST api/plugins/{id}/publish
    this.publishPlugin = makeOperation(http, "api/plugins", "POST", "{id}/publish");
    // POST api/plugins/{id}/republish (query: version)
    this.republishPlugin = makeOperation(http, "api/plugins", "POST", "{id}/republish", {"query":["version"]});
    // GET api/plugins/search (query: searchTerm)
    this.searchPlugins = makeOperation(http, "api/plugins", "GET", "search", {"query":["searchTerm"]});
    // POST api/plugins/{id}/uninstall
    this.uninstallPlugin = makeOperation(http, "api/plugins", "POST", "{id}/uninstall");
    // POST api/plugins/{id}/unpublish (query: version)
    this.unpublishPlugin = makeOperation(http, "api/plugins", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/plugins/{id}
    this.updatePlugin = makeOperation(http, "api/plugins", "PUT", "{id}");
  }
}

module.exports = { PluginsModule };
