'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/plugins (source: STAR WebAPI PluginsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class PluginsModule {
  constructor(http) {
    this._http = http;

    // post api/plugins/{id}/activate
    this.activatePlugin = makeOperation(http, "api/plugins", "POST", "{id}/activate");
    // post api/plugins/{id}/clone
    this.clonePlugin = makeOperation(http, "api/plugins", "POST", "{id}/clone");
    // post api/plugins/
    this.createPlugin = makeOperation(http, "api/plugins", "POST", "");
    // post api/plugins/create
    this.createPluginWithOptions = makeOperation(http, "api/plugins", "POST", "create");
    // post api/plugins/{id}/deactivate
    this.deactivatePlugin = makeOperation(http, "api/plugins", "POST", "{id}/deactivate");
    // delete api/plugins/{id}
    this.deletePlugin = makeOperation(http, "api/plugins", "DELETE", "{id}");
    // post api/plugins/{id}/download
    this.downloadPlugin = makeOperation(http, "api/plugins", "POST", "{id}/download");
    // post api/plugins/{id}/edit
    this.editPlugin = makeOperation(http, "api/plugins", "POST", "{id}/edit");
    // get api/plugins/
    this.getAllPlugins = makeOperation(http, "api/plugins", "GET", "");
    // get api/plugins/{id}
    this.getPlugin = makeOperation(http, "api/plugins", "GET", "{id}");
    // get api/plugins/{id}/versions
    this.getPluginVersions = makeOperation(http, "api/plugins", "GET", "{id}/versions");
    // get api/plugins/by-type/{type}
    this.getPluginsByType = makeOperation(http, "api/plugins", "GET", "by-type/{type}");
    // post api/plugins/{id}/install
    this.installPlugin = makeOperation(http, "api/plugins", "POST", "{id}/install");
    // get api/plugins/load-all-for-avatar
    this.loadAllPluginsForAvatar = makeOperation(http, "api/plugins", "GET", "load-all-for-avatar");
    // get api/plugins/{id}/load
    this.loadPlugin = makeOperation(http, "api/plugins", "GET", "{id}/load");
    // get api/plugins/load-from-path
    this.loadPluginFromPath = makeOperation(http, "api/plugins", "GET", "load-from-path");
    // get api/plugins/load-from-published
    this.loadPluginFromPublished = makeOperation(http, "api/plugins", "GET", "load-from-published");
    // get api/plugins/{id}/version/{version}
    this.loadPluginVersion = makeOperation(http, "api/plugins", "GET", "{id}/version/{version}");
    // post api/plugins/{id}/publish
    this.publishPlugin = makeOperation(http, "api/plugins", "POST", "{id}/publish");
    // post api/plugins/{id}/republish
    this.republishPlugin = makeOperation(http, "api/plugins", "POST", "{id}/republish");
    // get api/plugins/search
    this.searchPlugins = makeOperation(http, "api/plugins", "GET", "search");
    // post api/plugins/{id}/uninstall
    this.uninstallPlugin = makeOperation(http, "api/plugins", "POST", "{id}/uninstall");
    // post api/plugins/{id}/unpublish
    this.unpublishPlugin = makeOperation(http, "api/plugins", "POST", "{id}/unpublish");
    // put api/plugins/{id}
    this.updatePlugin = makeOperation(http, "api/plugins", "PUT", "{id}");
  }
}

module.exports = { PluginsModule };
