// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class QuestsModule {
  constructor(http: unknown);

  /** POST api/quests/{id}/activate */
  activateQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/objectives */
  addQuestObjective(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/subquests */
  addSubQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/progress */
  applyQuestProgress(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id}/can-start */
  canStartQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/clone */
  cloneQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/complete */
  completeQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/objectives/{objectiveId}/complete */
  completeQuestObjective(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/objectives/complete */
  completeQuestObjectiveByIdentifiers(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/ */
  createIQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/create */
  createQuestWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/deactivate */
  deactivateQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/quests/{id} */
  deleteIQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/download */
  downloadQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/edit */
  editQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/ */
  getAllIQuests(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/all-for-avatar */
  getAllQuestsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/all-for-avatar/game */
  getAllQuestsForAvatarGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id} */
  getIQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/by-avatar/{avatarId} */
  getIQuestsByAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id}/leaderboard */
  getQuestLeaderboard(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id}/rewards */
  getQuestRewards(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/by-status/{status} */
  getQuestsByStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/by-status/{status}/game */
  getQuestsByStatusGame(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/by-type/{type} */
  getQuestsByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/stats */
  getQuestStats(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id}/versions */
  getQuestVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/load-all-for-avatar */
  loadAllQuestsForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id}/load */
  loadQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/load-from-path */
  loadQuestFromPath(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/load-from-published */
  loadQuestFromPublished(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/{id}/version/{version} */
  loadQuestVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/publish */
  publishQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/quests/{parentId}/objectives/{objectiveId} */
  removeQuestObjective(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/quests/{parentId}/subquests/{subQuestId} */
  removeSubQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/republish */
  republishQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/progress/reset */
  resetObjectiveProgress(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/quests/search */
  searchQuests(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/start */
  startQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/quests/{id}/unpublish */
  unpublishQuest(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/quests/{id} */
  updateIQuest(args?: Record<string, any>): Promise<OASISResponse>;
}
