'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/quests (source: STAR WebAPI QuestsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class QuestsModule {
  constructor(http) {
    this._http = http;

    // post api/quests/{id}/activate
    this.activateQuest = makeOperation(http, "api/quests", "POST", "{id}/activate");
    // post api/quests/{id}/objectives
    this.addQuestObjective = makeOperation(http, "api/quests", "POST", "{id}/objectives");
    // post api/quests/{id}/subquests
    this.addSubQuest = makeOperation(http, "api/quests", "POST", "{id}/subquests");
    // post api/quests/{id}/progress
    this.applyQuestProgress = makeOperation(http, "api/quests", "POST", "{id}/progress");
    // get api/quests/{id}/can-start
    this.canStartQuest = makeOperation(http, "api/quests", "GET", "{id}/can-start");
    // post api/quests/{id}/clone
    this.cloneQuest = makeOperation(http, "api/quests", "POST", "{id}/clone");
    // post api/quests/{id}/complete
    this.completeQuest = makeOperation(http, "api/quests", "POST", "{id}/complete");
    // post api/quests/{id}/objectives/{objectiveId}/complete
    this.completeQuestObjective = makeOperation(http, "api/quests", "POST", "{id}/objectives/{objectiveId}/complete");
    // post api/quests/objectives/complete
    this.completeQuestObjectiveByIdentifiers = makeOperation(http, "api/quests", "POST", "objectives/complete");
    // post api/quests/
    this.createIQuest = makeOperation(http, "api/quests", "POST", "");
    // post api/quests/create
    this.createQuestWithOptions = makeOperation(http, "api/quests", "POST", "create");
    // post api/quests/{id}/deactivate
    this.deactivateQuest = makeOperation(http, "api/quests", "POST", "{id}/deactivate");
    // delete api/quests/{id}
    this.deleteIQuest = makeOperation(http, "api/quests", "DELETE", "{id}");
    // post api/quests/{id}/download
    this.downloadQuest = makeOperation(http, "api/quests", "POST", "{id}/download");
    // post api/quests/{id}/edit
    this.editQuest = makeOperation(http, "api/quests", "POST", "{id}/edit");
    // get api/quests/
    this.getAllIQuests = makeOperation(http, "api/quests", "GET", "");
    // get api/quests/all-for-avatar
    this.getAllQuestsForAvatar = makeOperation(http, "api/quests", "GET", "all-for-avatar");
    // get api/quests/all-for-avatar/game
    this.getAllQuestsForAvatarGame = makeOperation(http, "api/quests", "GET", "all-for-avatar/game");
    // get api/quests/{id}
    this.getIQuest = makeOperation(http, "api/quests", "GET", "{id}");
    // get api/quests/by-avatar/{avatarId}
    this.getIQuestsByAvatar = makeOperation(http, "api/quests", "GET", "by-avatar/{avatarId}");
    // get api/quests/{id}/leaderboard
    this.getQuestLeaderboard = makeOperation(http, "api/quests", "GET", "{id}/leaderboard");
    // get api/quests/{id}/rewards
    this.getQuestRewards = makeOperation(http, "api/quests", "GET", "{id}/rewards");
    // get api/quests/stats
    this.getQuestStats = makeOperation(http, "api/quests", "GET", "stats");
    // get api/quests/{id}/versions
    this.getQuestVersions = makeOperation(http, "api/quests", "GET", "{id}/versions");
    // get api/quests/by-status/{status}
    this.getQuestsByStatus = makeOperation(http, "api/quests", "GET", "by-status/{status}");
    // get api/quests/by-status/{status}/game
    this.getQuestsByStatusGame = makeOperation(http, "api/quests", "GET", "by-status/{status}/game");
    // get api/quests/by-type/{type}
    this.getQuestsByType = makeOperation(http, "api/quests", "GET", "by-type/{type}");
    // get api/quests/load-all-for-avatar
    this.loadAllQuestsForAvatar = makeOperation(http, "api/quests", "GET", "load-all-for-avatar");
    // get api/quests/{id}/load
    this.loadQuest = makeOperation(http, "api/quests", "GET", "{id}/load");
    // get api/quests/load-from-path
    this.loadQuestFromPath = makeOperation(http, "api/quests", "GET", "load-from-path");
    // get api/quests/load-from-published
    this.loadQuestFromPublished = makeOperation(http, "api/quests", "GET", "load-from-published");
    // get api/quests/{id}/version/{version}
    this.loadQuestVersion = makeOperation(http, "api/quests", "GET", "{id}/version/{version}");
    // post api/quests/{id}/publish
    this.publishQuest = makeOperation(http, "api/quests", "POST", "{id}/publish");
    // delete api/quests/{parentId}/objectives/{objectiveId}
    this.removeQuestObjective = makeOperation(http, "api/quests", "DELETE", "{parentId}/objectives/{objectiveId}");
    // delete api/quests/{parentId}/subquests/{subQuestId}
    this.removeSubQuest = makeOperation(http, "api/quests", "DELETE", "{parentId}/subquests/{subQuestId}");
    // post api/quests/{id}/republish
    this.republishQuest = makeOperation(http, "api/quests", "POST", "{id}/republish");
    // post api/quests/{id}/progress/reset
    this.resetObjectiveProgress = makeOperation(http, "api/quests", "POST", "{id}/progress/reset");
    // get api/quests/search
    this.searchQuests = makeOperation(http, "api/quests", "GET", "search");
    // post api/quests/{id}/start
    this.startQuest = makeOperation(http, "api/quests", "POST", "{id}/start");
    // post api/quests/{id}/unpublish
    this.unpublishQuest = makeOperation(http, "api/quests", "POST", "{id}/unpublish");
    // put api/quests/{id}
    this.updateIQuest = makeOperation(http, "api/quests", "PUT", "{id}");
  }
}

module.exports = { QuestsModule };
