'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/quests (source: STAR WebAPI QuestsController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class QuestsModule {
  constructor(http) {
    this._http = http;

    // POST api/quests/{id}/activate (query: version)
    this.activateQuest = makeOperation(http, "api/quests", "POST", "{id}/activate", {"query":["version"]});
    // POST api/quests/{id}/objectives
    this.addQuestObjective = makeOperation(http, "api/quests", "POST", "{id}/objectives");
    // POST api/quests/{id}/subquests
    this.addSubQuest = makeOperation(http, "api/quests", "POST", "{id}/subquests");
    // POST api/quests/{id}/progress
    this.applyQuestProgress = makeOperation(http, "api/quests", "POST", "{id}/progress");
    // GET api/quests/{id}/can-start
    this.canStartQuest = makeOperation(http, "api/quests", "GET", "{id}/can-start");
    // POST api/quests/{id}/clone
    this.cloneQuest = makeOperation(http, "api/quests", "POST", "{id}/clone");
    // POST api/quests/{id}/complete (body: completionNotes)
    this.completeQuest = makeOperation(http, "api/quests", "POST", "{id}/complete", {"bodyParam":"completionNotes"});
    // POST api/quests/{id}/objectives/{objectiveId}/complete
    this.completeQuestObjective = makeOperation(http, "api/quests", "POST", "{id}/objectives/{objectiveId}/complete");
    // POST api/quests/objectives/complete
    this.completeQuestObjectiveByIdentifiers = makeOperation(http, "api/quests", "POST", "objectives/complete");
    // POST api/quests/
    this.createIQuest = makeOperation(http, "api/quests", "POST", "");
    // POST api/quests/create
    this.createQuestWithOptions = makeOperation(http, "api/quests", "POST", "create");
    // POST api/quests/{id}/deactivate (query: version)
    this.deactivateQuest = makeOperation(http, "api/quests", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/quests/{id}
    this.deleteIQuest = makeOperation(http, "api/quests", "DELETE", "{id}");
    // POST api/quests/{id}/download (query: version, downloadPath, reInstall)
    this.downloadQuest = makeOperation(http, "api/quests", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/quests/{id}/edit
    this.editQuest = makeOperation(http, "api/quests", "POST", "{id}/edit");
    // GET api/quests/
    this.getAllIQuests = makeOperation(http, "api/quests", "GET", "");
    // GET api/quests/all-for-avatar
    this.getAllQuestsForAvatar = makeOperation(http, "api/quests", "GET", "all-for-avatar");
    // GET api/quests/all-for-avatar/game
    this.getAllQuestsForAvatarGame = makeOperation(http, "api/quests", "GET", "all-for-avatar/game");
    // GET api/quests/{id}
    this.getIQuest = makeOperation(http, "api/quests", "GET", "{id}");
    // GET api/quests/by-avatar/{avatarId}
    this.getIQuestsByAvatar = makeOperation(http, "api/quests", "GET", "by-avatar/{avatarId}");
    // GET api/quests/{id}/leaderboard (query: limit)
    this.getQuestLeaderboard = makeOperation(http, "api/quests", "GET", "{id}/leaderboard", {"query":["limit"]});
    // GET api/quests/{id}/rewards
    this.getQuestRewards = makeOperation(http, "api/quests", "GET", "{id}/rewards");
    // GET api/quests/stats
    this.getQuestStats = makeOperation(http, "api/quests", "GET", "stats");
    // GET api/quests/{id}/versions
    this.getQuestVersions = makeOperation(http, "api/quests", "GET", "{id}/versions");
    // GET api/quests/by-status/{status}
    this.getQuestsByStatus = makeOperation(http, "api/quests", "GET", "by-status/{status}");
    // GET api/quests/by-status/{status}/game
    this.getQuestsByStatusGame = makeOperation(http, "api/quests", "GET", "by-status/{status}/game");
    // GET api/quests/by-type/{type}
    this.getQuestsByType = makeOperation(http, "api/quests", "GET", "by-type/{type}");
    // GET api/quests/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllQuestsForAvatar = makeOperation(http, "api/quests", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/quests/{id}/load (query: version, holonType)
    this.loadQuest = makeOperation(http, "api/quests", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/quests/load-from-path (query: path, holonType)
    this.loadQuestFromPath = makeOperation(http, "api/quests", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/quests/load-from-published (query: publishedFilePath)
    this.loadQuestFromPublished = makeOperation(http, "api/quests", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/quests/{id}/version/{version}
    this.loadQuestVersion = makeOperation(http, "api/quests", "GET", "{id}/version/{version}");
    // POST api/quests/{id}/publish
    this.publishQuest = makeOperation(http, "api/quests", "POST", "{id}/publish");
    // DELETE api/quests/{parentId}/objectives/{objectiveId}
    this.removeQuestObjective = makeOperation(http, "api/quests", "DELETE", "{parentId}/objectives/{objectiveId}");
    // DELETE api/quests/{parentId}/subquests/{subQuestId}
    this.removeSubQuest = makeOperation(http, "api/quests", "DELETE", "{parentId}/subquests/{subQuestId}");
    // POST api/quests/{id}/republish (query: version)
    this.republishQuest = makeOperation(http, "api/quests", "POST", "{id}/republish", {"query":["version"]});
    // POST api/quests/{id}/progress/reset
    this.resetObjectiveProgress = makeOperation(http, "api/quests", "POST", "{id}/progress/reset");
    // GET api/quests/search (query: query)
    this.searchQuests = makeOperation(http, "api/quests", "GET", "search", {"query":["query"]});
    // POST api/quests/{id}/unpublish (query: version)
    this.unpublishQuest = makeOperation(http, "api/quests", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/quests/{id}
    this.updateIQuest = makeOperation(http, "api/quests", "PUT", "{id}");
  }
}

module.exports = { QuestsModule };
