'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/runtimes (source: STAR WebAPI RuntimesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class RuntimesModule {
  constructor(http) {
    this._http = http;

    // POST api/runtimes/{id}/activate
    this.activateRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/activate");
    // POST api/runtimes/{id}/clone
    this.cloneRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/clone");
    // POST api/runtimes/
    this.createRuntime = makeOperation(http, "api/runtimes", "POST", "");
    // POST api/runtimes/create
    this.createRuntimeWithOptions = makeOperation(http, "api/runtimes", "POST", "create");
    // POST api/runtimes/{id}/deactivate
    this.deactivateRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/deactivate");
    // DELETE api/runtimes/{id}
    this.deleteRuntime = makeOperation(http, "api/runtimes", "DELETE", "{id}");
    // POST api/runtimes/{id}/download
    this.downloadRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/download");
    // PUT api/runtimes/{id}/edit
    this.editRuntime = makeOperation(http, "api/runtimes", "PUT", "{id}/edit");
    // GET api/runtimes/
    this.getAllRuntimes = makeOperation(http, "api/runtimes", "GET", "");
    // GET api/runtimes/{id}
    this.getRuntime = makeOperation(http, "api/runtimes", "GET", "{id}");
    // GET api/runtimes/{id}/status
    this.getRuntimeStatus = makeOperation(http, "api/runtimes", "GET", "{id}/status");
    // GET api/runtimes/{id}/versions
    this.getRuntimeVersions = makeOperation(http, "api/runtimes", "GET", "{id}/versions");
    // GET api/runtimes/by-type/{type}
    this.getRuntimesByType = makeOperation(http, "api/runtimes", "GET", "by-type/{type}");
    // GET api/runtimes/load-all-for-avatar
    this.loadAllRuntimesForAvatar = makeOperation(http, "api/runtimes", "GET", "load-all-for-avatar");
    // GET api/runtimes/load-from-path (query: path)
    this.loadRuntimeFromPath = makeOperation(http, "api/runtimes", "GET", "load-from-path", {"query":["path"]});
    // GET api/runtimes/load-from-published (query: publishedFilePath)
    this.loadRuntimeFromPublished = makeOperation(http, "api/runtimes", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/runtimes/{id}/versions/{version}
    this.loadRuntimeVersion = makeOperation(http, "api/runtimes", "GET", "{id}/versions/{version}");
    // POST api/runtimes/{id}/publish
    this.publishRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/publish");
    // POST api/runtimes/{id}/republish
    this.republishRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/republish");
    // GET api/runtimes/search (query: searchTerm)
    this.searchRuntimes = makeOperation(http, "api/runtimes", "GET", "search", {"query":["searchTerm"]});
    // POST api/runtimes/{id}/start
    this.startRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/start");
    // POST api/runtimes/{id}/stop
    this.stopRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/stop");
    // POST api/runtimes/{id}/unpublish
    this.unpublishRuntime = makeOperation(http, "api/runtimes", "POST", "{id}/unpublish");
    // PUT api/runtimes/{id}
    this.updateRuntime = makeOperation(http, "api/runtimes", "PUT", "{id}");
  }
}

module.exports = { RuntimesModule };
