'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/sTAR (source: STAR WebAPI STARController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class STARModule {
  constructor(http) {
    this._http = http;

    // POST api/sTAR/beam-in
    this.beamIn = makeOperation(http, "api/sTAR", "POST", "beam-in");
    // POST api/sTAR/extinguish
    this.extinguishSTAR = makeOperation(http, "api/sTAR", "POST", "extinguish");
    // GET api/sTAR/status
    this.getStatus = makeOperation(http, "api/sTAR", "GET", "status");
    // POST api/sTAR/ignite
    this.igniteSTAR = makeOperation(http, "api/sTAR", "POST", "ignite");
  }
}

module.exports = { STARModule };
