// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class STARModule {
  constructor(http: unknown);

  /** POST api/sTAR/beam-in */
  beamIn(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/sTAR/extinguish */
  extinguishSTAR(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/sTAR/status */
  getStatus(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/sTAR/ignite */
  igniteSTAR(args?: Record<string, any>): Promise<OASISResponse>;
}
