'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/templates (source: STAR WebAPI TemplatesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class TemplatesModule {
  constructor(http) {
    this._http = http;

    // POST api/templates/{id}/activate
    this.activateTemplate = makeOperation(http, "api/templates", "POST", "{id}/activate");
    // POST api/templates/{id}/clone
    this.cloneTemplate = makeOperation(http, "api/templates", "POST", "{id}/clone");
    // POST api/templates/
    this.createTemplate = makeOperation(http, "api/templates", "POST", "");
    // POST api/templates/create
    this.createTemplateWithOptions = makeOperation(http, "api/templates", "POST", "create");
    // POST api/templates/{id}/deactivate
    this.deactivateTemplate = makeOperation(http, "api/templates", "POST", "{id}/deactivate");
    // DELETE api/templates/{id}
    this.deleteTemplate = makeOperation(http, "api/templates", "DELETE", "{id}");
    // POST api/templates/{id}/download
    this.downloadTemplate = makeOperation(http, "api/templates", "POST", "{id}/download");
    // PUT api/templates/{id}/edit
    this.editTemplate = makeOperation(http, "api/templates", "PUT", "{id}/edit");
    // GET api/templates/
    this.getAllTemplates = makeOperation(http, "api/templates", "GET", "");
    // GET api/templates/{id}
    this.getTemplate = makeOperation(http, "api/templates", "GET", "{id}");
    // GET api/templates/{id}/versions
    this.getTemplateVersions = makeOperation(http, "api/templates", "GET", "{id}/versions");
    // GET api/templates/by-type/{type}
    this.getTemplatesByType = makeOperation(http, "api/templates", "GET", "by-type/{type}");
    // GET api/templates/load-all-for-avatar
    this.loadAllTemplatesForAvatar = makeOperation(http, "api/templates", "GET", "load-all-for-avatar");
    // GET api/templates/load-from-path (query: path)
    this.loadTemplateFromPath = makeOperation(http, "api/templates", "GET", "load-from-path", {"query":["path"]});
    // GET api/templates/load-from-published (query: publishedFilePath)
    this.loadTemplateFromPublished = makeOperation(http, "api/templates", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/templates/{id}/versions/{version}
    this.loadTemplateVersion = makeOperation(http, "api/templates", "GET", "{id}/versions/{version}");
    // POST api/templates/{id}/publish
    this.publishTemplate = makeOperation(http, "api/templates", "POST", "{id}/publish");
    // POST api/templates/{id}/republish
    this.republishTemplate = makeOperation(http, "api/templates", "POST", "{id}/republish");
    // GET api/templates/search (query: searchTerm)
    this.searchTemplates = makeOperation(http, "api/templates", "GET", "search", {"query":["searchTerm"]});
    // POST api/templates/{id}/unpublish
    this.unpublishTemplate = makeOperation(http, "api/templates", "POST", "{id}/unpublish");
    // PUT api/templates/{id}
    this.updateTemplate = makeOperation(http, "api/templates", "PUT", "{id}");
  }
}

module.exports = { TemplatesModule };
