// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class TemplatesModule {
  constructor(http: unknown);

  /** POST api/templates/{id}/activate */
  activateTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/{id}/clone */
  cloneTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/ */
  createTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/create */
  createTemplateWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/{id}/deactivate */
  deactivateTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/templates/{id} */
  deleteTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/{id}/download */
  downloadTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/templates/{id}/edit */
  editTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/templates/ */
  getAllTemplates(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/templates/{id} */
  getTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/templates/by-type/{type} */
  getTemplatesByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/templates/{id}/versions */
  getTemplateVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/templates/load-all-for-avatar */
  loadAllTemplatesForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/templates/{id}/versions/{version} */
  loadTemplateVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/{id}/publish */
  publishTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/{id}/republish */
  republishTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/search */
  searchTemplatesPost(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/templates/{id}/unpublish */
  unpublishTemplate(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/templates/{id} */
  updateTemplate(args?: Record<string, any>): Promise<OASISResponse>;
}
