// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ZomesMetaDataModule {
  constructor(http: unknown);

  /** POST api/zomesMetaData/{id}/activate */
  activateZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/{id}/clone */
  cloneZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/ */
  createZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/create */
  createZomeMetaDataWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/{id}/deactivate */
  deactivateZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/zomesMetaData/{id} */
  deleteZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/{id}/download */
  downloadZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/zomesMetaData/{id}/edit */
  editZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/ */
  getAllZomesMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/{id} */
  getZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/{id}/versions */
  getZomeMetaDataVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/load-all-for-avatar */
  loadAllZomeMetaDataForAvatar(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/load-from-path */
  loadZomeMetaDataFromPath(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/load-from-published */
  loadZomeMetaDataFromPublished(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/{id}/versions/{version} */
  loadZomeMetaDataVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/{id}/publish */
  publishZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/{id}/republish */
  republishZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomesMetaData/search */
  searchZomesMetaDataGet(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/search */
  searchZomesMetaDataPost(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomesMetaData/{id}/unpublish */
  unpublishZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/zomesMetaData/{id} */
  updateZomeMetaData(args?: Record<string, any>): Promise<OASISResponse>;
}
