'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/zomes (source: STAR WebAPI ZomesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ZomesModule {
  constructor(http) {
    this._http = http;

    // POST api/zomes/{id}/activate (query: version)
    this.activateZome = makeOperation(http, "api/zomes", "POST", "{id}/activate", {"query":["version"]});
    // POST api/zomes/
    this.createZome = makeOperation(http, "api/zomes", "POST", "");
    // POST api/zomes/create
    this.createZomeWithOptions = makeOperation(http, "api/zomes", "POST", "create");
    // POST api/zomes/{id}/deactivate (query: version)
    this.deactivateZome = makeOperation(http, "api/zomes", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/zomes/{id}
    this.deleteZome = makeOperation(http, "api/zomes", "DELETE", "{id}");
    // POST api/zomes/{id}/download (query: version, downloadPath, reInstall)
    this.downloadZome = makeOperation(http, "api/zomes", "POST", "{id}/download", {"query":["version","downloadPath","reInstall"]});
    // POST api/zomes/{id}/edit
    this.editZome = makeOperation(http, "api/zomes", "POST", "{id}/edit");
    // GET api/zomes/
    this.getAllZomes = makeOperation(http, "api/zomes", "GET", "");
    // GET api/zomes/{id}
    this.getZome = makeOperation(http, "api/zomes", "GET", "{id}");
    // GET api/zomes/{id}/versions
    this.getZomeVersions = makeOperation(http, "api/zomes", "GET", "{id}/versions");
    // GET api/zomes/by-type/{type}
    this.getZomesByType = makeOperation(http, "api/zomes", "GET", "by-type/{type}");
    // GET api/zomes/in-space/{spaceId}
    this.getZomesInSpace = makeOperation(http, "api/zomes", "GET", "in-space/{spaceId}");
    // GET api/zomes/load-all-for-avatar (query: showAllVersions, version)
    this.loadAllZomesForAvatar = makeOperation(http, "api/zomes", "GET", "load-all-for-avatar", {"query":["showAllVersions","version"]});
    // GET api/zomes/{id}/load (query: version, holonType)
    this.loadZome = makeOperation(http, "api/zomes", "GET", "{id}/load", {"query":["version","holonType"]});
    // GET api/zomes/load-from-path (query: path, holonType)
    this.loadZomeFromPath = makeOperation(http, "api/zomes", "GET", "load-from-path", {"query":["path","holonType"]});
    // GET api/zomes/load-from-published (query: publishedFilePath)
    this.loadZomeFromPublished = makeOperation(http, "api/zomes", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/zomes/{id}/version/{version}
    this.loadZomeVersion = makeOperation(http, "api/zomes", "GET", "{id}/version/{version}");
    // POST api/zomes/{id}/publish
    this.publishZome = makeOperation(http, "api/zomes", "POST", "{id}/publish");
    // POST api/zomes/{id}/republish (query: version)
    this.republishZome = makeOperation(http, "api/zomes", "POST", "{id}/republish", {"query":["version"]});
    // GET api/zomes/search (query: searchTerm, searchOnlyForCurrentAvatar, showAllVersions, version)
    this.searchZomes = makeOperation(http, "api/zomes", "GET", "search", {"query":["searchTerm","searchOnlyForCurrentAvatar","showAllVersions","version"]});
    // POST api/zomes/{id}/unpublish (query: version)
    this.unpublishZome = makeOperation(http, "api/zomes", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/zomes/{id}
    this.updateZome = makeOperation(http, "api/zomes", "PUT", "{id}");
  }
}

module.exports = { ZomesModule };
