'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/zomes (source: STAR WebAPI ZomesController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ZomesModule {
  constructor(http) {
    this._http = http;

    // post api/zomes/{id}/activate
    this.activateZome = makeOperation(http, "api/zomes", "POST", "{id}/activate");
    // post api/zomes/
    this.createZome = makeOperation(http, "api/zomes", "POST", "");
    // post api/zomes/create
    this.createZomeWithOptions = makeOperation(http, "api/zomes", "POST", "create");
    // post api/zomes/{id}/deactivate
    this.deactivateZome = makeOperation(http, "api/zomes", "POST", "{id}/deactivate");
    // delete api/zomes/{id}
    this.deleteZome = makeOperation(http, "api/zomes", "DELETE", "{id}");
    // post api/zomes/{id}/download
    this.downloadZome = makeOperation(http, "api/zomes", "POST", "{id}/download");
    // post api/zomes/{id}/edit
    this.editZome = makeOperation(http, "api/zomes", "POST", "{id}/edit");
    // get api/zomes/
    this.getAllZomes = makeOperation(http, "api/zomes", "GET", "");
    // get api/zomes/{id}
    this.getZome = makeOperation(http, "api/zomes", "GET", "{id}");
    // get api/zomes/{id}/versions
    this.getZomeVersions = makeOperation(http, "api/zomes", "GET", "{id}/versions");
    // get api/zomes/by-type/{type}
    this.getZomesByType = makeOperation(http, "api/zomes", "GET", "by-type/{type}");
    // get api/zomes/in-space/{spaceId}
    this.getZomesInSpace = makeOperation(http, "api/zomes", "GET", "in-space/{spaceId}");
    // get api/zomes/load-all-for-avatar
    this.loadAllZomesForAvatar = makeOperation(http, "api/zomes", "GET", "load-all-for-avatar");
    // get api/zomes/{id}/load
    this.loadZome = makeOperation(http, "api/zomes", "GET", "{id}/load");
    // get api/zomes/load-from-path
    this.loadZomeFromPath = makeOperation(http, "api/zomes", "GET", "load-from-path");
    // get api/zomes/load-from-published
    this.loadZomeFromPublished = makeOperation(http, "api/zomes", "GET", "load-from-published");
    // get api/zomes/{id}/version/{version}
    this.loadZomeVersion = makeOperation(http, "api/zomes", "GET", "{id}/version/{version}");
    // post api/zomes/{id}/publish
    this.publishZome = makeOperation(http, "api/zomes", "POST", "{id}/publish");
    // post api/zomes/{id}/republish
    this.republishZome = makeOperation(http, "api/zomes", "POST", "{id}/republish");
    // get api/zomes/search
    this.searchZomes = makeOperation(http, "api/zomes", "GET", "search");
    // post api/zomes/{id}/unpublish
    this.unpublishZome = makeOperation(http, "api/zomes", "POST", "{id}/unpublish");
    // put api/zomes/{id}
    this.updateZome = makeOperation(http, "api/zomes", "PUT", "{id}");
  }
}

module.exports = { ZomesModule };
