// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ZomesModule {
  constructor(http: unknown);

  /** POST api/zomes/ */
  createZome(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomes/create */
  createZomeWithOptions(args?: Record<string, any>): Promise<OASISResponse>;

  /** DELETE api/zomes/{id} */
  deleteZome(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomes/{id}/edit */
  editZome(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomes/ */
  getAllZomes(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomes/{id} */
  getZome(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomes/by-type/{type} */
  getZomesByType(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomes/in-space/{spaceId} */
  getZomesInSpace(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomes/{id}/versions */
  getZomeVersions(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET api/zomes/{id}/version/{version} */
  loadZomeVersion(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST api/zomes/{id}/publish */
  publishZome(args?: Record<string, any>): Promise<OASISResponse>;

  /** PUT api/zomes/{id} */
  updateZome(args?: Record<string, any>): Promise<OASISResponse>;
}
