'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/zomesMetaData (source: STAR WebAPI ZomesMetaDataController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ZomesMetaDataModule {
  constructor(http) {
    this._http = http;

    // post api/zomesMetaData/{id}/activate
    this.activateZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/activate");
    // post api/zomesMetaData/{id}/clone
    this.cloneZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/clone");
    // post api/zomesMetaData/
    this.createZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "");
    // post api/zomesMetaData/create
    this.createZomeMetaDataWithOptions = makeOperation(http, "api/zomesMetaData", "POST", "create");
    // post api/zomesMetaData/{id}/deactivate
    this.deactivateZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/deactivate");
    // delete api/zomesMetaData/{id}
    this.deleteZomeMetaData = makeOperation(http, "api/zomesMetaData", "DELETE", "{id}");
    // post api/zomesMetaData/{id}/download
    this.downloadZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/download");
    // put api/zomesMetaData/{id}/edit
    this.editZomeMetaData = makeOperation(http, "api/zomesMetaData", "PUT", "{id}/edit");
    // get api/zomesMetaData/
    this.getAllZomesMetaData = makeOperation(http, "api/zomesMetaData", "GET", "");
    // get api/zomesMetaData/{id}
    this.getZomeMetaData = makeOperation(http, "api/zomesMetaData", "GET", "{id}");
    // get api/zomesMetaData/{id}/versions
    this.getZomeMetaDataVersions = makeOperation(http, "api/zomesMetaData", "GET", "{id}/versions");
    // get api/zomesMetaData/load-all-for-avatar
    this.loadAllZomeMetaDataForAvatar = makeOperation(http, "api/zomesMetaData", "GET", "load-all-for-avatar");
    // get api/zomesMetaData/load-from-path
    this.loadZomeMetaDataFromPath = makeOperation(http, "api/zomesMetaData", "GET", "load-from-path");
    // get api/zomesMetaData/load-from-published
    this.loadZomeMetaDataFromPublished = makeOperation(http, "api/zomesMetaData", "GET", "load-from-published");
    // get api/zomesMetaData/{id}/versions/{version}
    this.loadZomeMetaDataVersion = makeOperation(http, "api/zomesMetaData", "GET", "{id}/versions/{version}");
    // post api/zomesMetaData/{id}/publish
    this.publishZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/publish");
    // post api/zomesMetaData/{id}/republish
    this.republishZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/republish");
    // get api/zomesMetaData/search
    this.searchZomesMetaDataGet = makeOperation(http, "api/zomesMetaData", "GET", "search");
    // post api/zomesMetaData/search
    this.searchZomesMetaDataPost = makeOperation(http, "api/zomesMetaData", "POST", "search");
    // post api/zomesMetaData/{id}/unpublish
    this.unpublishZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/unpublish");
    // put api/zomesMetaData/{id}
    this.updateZomeMetaData = makeOperation(http, "api/zomesMetaData", "PUT", "{id}");
  }
}

module.exports = { ZomesMetaDataModule };
