'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for api/zomesMetaData (source: STAR WebAPI ZomesMetaDataController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ZomesMetaDataModule {
  constructor(http) {
    this._http = http;

    // POST api/zomesMetaData/{id}/activate (query: version)
    this.activateZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/activate", {"query":["version"]});
    // POST api/zomesMetaData/{id}/clone
    this.cloneZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/clone");
    // POST api/zomesMetaData/
    this.createZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "");
    // POST api/zomesMetaData/create
    this.createZomeMetaDataWithOptions = makeOperation(http, "api/zomesMetaData", "POST", "create");
    // POST api/zomesMetaData/{id}/deactivate (query: version)
    this.deactivateZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/deactivate", {"query":["version"]});
    // DELETE api/zomesMetaData/{id}
    this.deleteZomeMetaData = makeOperation(http, "api/zomesMetaData", "DELETE", "{id}");
    // POST api/zomesMetaData/{id}/download
    this.downloadZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/download");
    // PUT api/zomesMetaData/{id}/edit
    this.editZomeMetaData = makeOperation(http, "api/zomesMetaData", "PUT", "{id}/edit");
    // GET api/zomesMetaData/
    this.getAllZomesMetaData = makeOperation(http, "api/zomesMetaData", "GET", "");
    // GET api/zomesMetaData/{id}
    this.getZomeMetaData = makeOperation(http, "api/zomesMetaData", "GET", "{id}");
    // GET api/zomesMetaData/{id}/versions
    this.getZomeMetaDataVersions = makeOperation(http, "api/zomesMetaData", "GET", "{id}/versions");
    // GET api/zomesMetaData/load-all-for-avatar
    this.loadAllZomeMetaDataForAvatar = makeOperation(http, "api/zomesMetaData", "GET", "load-all-for-avatar");
    // GET api/zomesMetaData/load-from-path (query: path)
    this.loadZomeMetaDataFromPath = makeOperation(http, "api/zomesMetaData", "GET", "load-from-path", {"query":["path"]});
    // GET api/zomesMetaData/load-from-published (query: publishedFilePath)
    this.loadZomeMetaDataFromPublished = makeOperation(http, "api/zomesMetaData", "GET", "load-from-published", {"query":["publishedFilePath"]});
    // GET api/zomesMetaData/{id}/versions/{version}
    this.loadZomeMetaDataVersion = makeOperation(http, "api/zomesMetaData", "GET", "{id}/versions/{version}");
    // POST api/zomesMetaData/{id}/publish
    this.publishZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/publish");
    // POST api/zomesMetaData/{id}/republish (query: version)
    this.republishZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/republish", {"query":["version"]});
    // POST api/zomesMetaData/search
    this.searchZomesMetaData = makeOperation(http, "api/zomesMetaData", "POST", "search");
    // POST api/zomesMetaData/{id}/unpublish (query: version)
    this.unpublishZomeMetaData = makeOperation(http, "api/zomesMetaData", "POST", "{id}/unpublish", {"query":["version"]});
    // PUT api/zomesMetaData/{id}
    this.updateZomeMetaData = makeOperation(http, "api/zomesMetaData", "PUT", "{id}");
  }
}

module.exports = { ZomesMetaDataModule };
